"""DataGen 各阶段共用的正式产物和控制文件名。"""

WORKFLOW_VERSION = "3.0"
RESEARCH_GUIDE_FILE = "RESEARCH_GUIDE.md"
INTEGRATION_GUIDE_FILE = "INTEGRATION_GUIDE.md"
CONTROL_DIRECTORY = ".datagen"
CONTROL_RUN_CONFIG = "run_config.json"
CONTROL_RAW_INTEGRITY_SNAPSHOT = "raw_integrity_snapshot.json"
CONTROL_COLLECTION_RESULT = "collection_result.json"
CONTROL_INTEGRATION_LAUNCHER = "integratectl"
CONTROL_DOWNLOAD_RECEIPTS = "download_receipts.json"
CONTROL_SCENARIO_RESEARCH_RECEIPT = "scenario_research_receipt.json"
CONTROL_SOURCE_RESEARCH_RECEIPT = "source_research_receipt.json"
CONTROL_SELECTED_SEED = "selected_seed.json"
CONTROL_PREPARATION_MANIFEST = "preparation_manifest.json"
CONTROL_SOURCE_FINALIZATION = "source_finalization.json"
CONTROL_INTEGRATION_ASSESSMENT = "integration_assessment.json"
CONTROL_INTEGRATION_FINALIZATION = "integration_finalization.json"

SCENARIO_RESEARCH_PATH = "provenance/scenario_research.json"
SOURCE_RESEARCH_PATH = "provenance/source_research.json"
SOURCE_INVENTORY_PATH = "provenance/source_inventory.json"
COLLECTION_PROFILE_PATH = ".datagen/collection_profile.json"
INTEGRATION_BUILD_PATH = "provenance/build.py"
INTEGRATION_RECEIPT_PATH = "provenance/integration_receipt.json"
SOURCE_MANIFEST_PATH = "provenance/source_manifest.json"
FREEZE_MANIFEST_PATH = "provenance/freeze_manifest.json"
ENVIRONMENT_CONTEXT_PATH = "environment.md"
