"""Author explicit, capability-balanced profiles for the materials batch.

The generated profiles contain symbol names and method names explicitly; this
helper only materializes them against the pinned raw indexes and never ranks
or silently truncates APIs.
"""
from __future__ import annotations

import json
from pathlib import Path
from seed_gen.scripts.select_python_ref_tools import _canonical_sha256

ROOT = Path("seed_gen/pypi_outputs/ori_all")
OUT = Path("seed_gen/pypi_selection_profiles")

def C(cid, description, reason, symbols, verification, sources):
    return {"id": cid, "description": description, "selection_reason": reason,
            "symbols": symbols, "evidence_sources": sources,
            "evidence": ["public_api", "core_capability", "composable_io"],
            "verification_tier": verification}

def cls(module, name, methods):
    return {"module": module, "name": name, "type": "class", "methods": methods}

def fn(module, name):
    return {"module": module, "name": name, "type": "function"}

def funcs(module, names):
    return [fn(module, name) for name in names]

RULES = {
"mp-api_v0.46.5": {
 "profile_id": "mp_api_materials_explorer_v1", "boundary": "Materials Project 查询客户端、结构/热力学/电子结构检索和统一响应；排除贡献者管理、MCP 服务和内部认证辅助。", "target": (50, 100),
 "caps": [
  C("materials_query", "材料结构、条目和任务查询", "MPRester 是官方高层入口，保留结构、条目、化学体系和任务查询闭环。", [cls("mp_api.client.mprester", "MPRester", ["__init__", "get_structure_by_material_id", "get_material_ids", "get_structures", "find_structure", "get_entries", "get_entries_in_chemsys", "get_entry_by_material_id", "get_task_ids_associated_with_material_id", "get_material_id_from_task_id", "get_download_info", "query"]), cls("mp_api.client.routes.materials.materials", "MaterialsRester", ["search", "find_structure", "get_structure_by_material_id"]), cls("mp_api.client.routes.materials.summary", "SummaryRester", ["search"])], "api_fixture_planned", ["seed_pypi_raw/mp-api/mp_api/client/mprester.py"]),
  C("property_query", "热力学、电子结构和声子性质查询", "代表性 rester 覆盖常用材料性质并能串接 material_id。", [cls("mp_api.client.routes.materials.thermo", "ThermoRester", ["search", "get_phase_diagram_from_chemsys"]), cls("mp_api.client.routes.materials.electronic_structure", "BandStructureRester", ["search", "search_bandstructure_summary", "get_bandstructure_from_material_id"]), cls("mp_api.client.routes.materials.electronic_structure", "DosRester", ["search", "search_dos_summary", "get_dos_from_material_id"]), cls("mp_api.client.routes.materials.phonon", "PhononRester", ["search", "get_bandstructure_from_material_id", "get_dos_from_material_id", "compute_thermo_quantities"]), cls("mp_api.client.routes.materials.similarity", "SimilarityRester", ["fingerprint_structure", "search", "find_similar"])], "record_schema_planned", ["seed_pypi_raw/mp-api/mp_api/client/routes/materials"]),
  C("response_models", "数据集和 MCP 响应模型", "保留数据集读取及最小响应转换接口，便于离线固定响应验证。", [cls("mp_api.client.core.client", "BaseRester", ["__init__", "get_data_by_id", "count", "available_fields"]), cls("mp_api.client.core.utils", "MPDataset", ["__init__", "pyarrow_dataset", "pydantic_model", "num_chunks"]), cls("mp_api.mcp.tools", "MPCoreMCP", ["search", "fetch", "fetch_many", "fetch_all", "get_phase_diagram_from_elements"])], "offline_response_fixture_planned", ["seed_pypi_raw/mp-api/mp_api/client/core"]),
 ]},
"ase_3.29.0": {
 "profile_id": "ase_structure_simulation_v1", "boundary": "ASE 原子结构、构造、通用文件 I/O、计算器协议和优化入口；排除外部软件专用长尾计算器及内部 _4 实验 API。", "target": (50, 100),
 "caps": [
  C("atoms", "原子结构与性质访问", "Atoms/Atom 是跨计算器工作流的核心实体，保留本发布源码直接定义的构造、计算器绑定和能量/力性质接口；继承方法不重复展开。", [cls("ase.atoms", "Atoms", ["__init__", "set_calculator", "get_calculator", "calc", "get_magnetic_moments", "get_magnetic_moment", "get_charges", "get_potential_energy", "get_properties", "get_potential_energies", "get_total_energy", "get_forces", "get_stress", "get_stresses", "get_kinetic_stresses", "get_dipole_moment"]), cls("ase.atom", "Atom", ["__init__", "scaled_position", "cut_reference_to_atoms", "get_raw", "get", "set", "delete"])], "emt_fixture_planned", ["seed_pypi_raw/ase/ase/atoms.py", "seed_pypi_raw/ase/ase/atom.py"]),
  C("builders", "晶体、分子、表面和超胞构造", "保留常见材料结构构造函数以及超胞变换，覆盖从元素到可计算结构的输入阶段。", [*funcs("ase.build.bulk", ["bulk"]), *funcs("ase.build.molecule", ["molecule"]), *funcs("ase.build.surface", ["fcc100", "fcc111", "bcc110", "hcp0001", "add_adsorbate", "add_vacuum", "graphene"]), *funcs("ase.build.supercells", ["find_optimal_cell_shape", "make_supercell", "lattice_points_in_supercell"]), *funcs("ase.build.tools", ["cut", "stack", "rotate", "sort"]), *funcs("ase.build.connected", ["connected_atoms", "separate"]), fn("ase.build.ribbon", "graphene_nanoribbon"), fn("ase.build.tube", "nanotube")], "structure_fixture_planned", ["seed_pypi_raw/ase/ase/build"]),
  C("io", "结构文件读写和轨迹", "通用 read/write、CIF/XYZ/VASP 和轨迹接口可形成可复现的结构 round-trip。", [*funcs("ase.io.formats", ["read", "iread", "write", "parse_filename"]), *funcs("ase.io.cif", ["read_cif", "iread_cif", "write_cif"]), *funcs("ase.io.xyz", ["read_xyz", "write_xyz"]), *funcs("ase.io.vasp", ["read_vasp", "read_vasp_out", "write_vasp", "write_vasp_xdatcar"]), fn("ase.io.trajectory", "Trajectory"), cls("ase.io.trajectory", "TrajectoryWriter", ["__init__", "set_description", "write", "close"]), cls("ase.io.trajectory", "TrajectoryReader", ["__init__", "close"])], "roundtrip_fixture_planned", ["seed_pypi_raw/ase/ase/io"]),
  C("calculator_protocol", "计算器协议和轻量 EMT", "Calculator 基类及 EMT 提供无需外部程序的最小能量/力验证入口。", [cls("ase.calculators.calculator", "Calculator", ["__init__", "set", "calculate", "check_state", "todict", "reset", "get_atoms"]), cls("ase.calculators.emt", "EMT", ["__init__", "initialize", "calculate"]), cls("ase.optimize.optimize", "Optimizer", ["__init__", "run", "irun", "converged", "log", "replay_trajectory"]), cls("ase.optimize.bfgs", "BFGS", ["__init__", "initialize", "step", "prepare_step", "update"]), cls("ase.optimize.fire", "FIRE", ["__init__", "initialize", "step"])], "emt_optimization_planned", ["seed_pypi_raw/ase/ase/calculators/calculator.py", "seed_pypi_raw/ase/ase/calculators/emt.py"]),
 ]},
"matminer_v0.10.1": {
 "profile_id": "matminer_feature_engineering_v1", "boundary": "材料数据集加载和代表性组成、结构、位点特征工程；不展开数百个同类 featurizer、联网检索和测试工具。", "target": (50, 100),
 "caps": [
  C("datasets", "数据集加载与表格转换", "保留稳定的本地数据集入口和 DataFrame 加载接口。", [fn("matminer.datasets.dataset_retrieval", "load_dataset"), fn("matminer.datasets.dataset_retrieval", "get_available_datasets"), fn("matminer.datasets.dataset_retrieval", "get_dataset_columns"), fn("matminer.datasets.dataset_retrieval", "get_dataset_description"), fn("matminer.datasets.dataset_retrieval", "get_all_dataset_info"), fn("matminer.utils.io", "store_dataframe_as_json")], "local_dataset_planned", ["seed_pypi_raw/matminer/src/matminer/datasets"]),
  C("composition_features", "组成和元素特征", "选取元素分数、元素属性、离子和热力学代表类，覆盖组成到数值特征的闭环。", [cls("matminer.featurizers.composition.element", "ElementFraction", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.composition.composite", "ElementProperty", ["__init__", "from_preset", "featurize", "feature_labels"]), cls("matminer.featurizers.composition.ion", "CationProperty", ["from_preset", "featurize", "feature_labels"]), cls("matminer.featurizers.composition.orbital", "AtomicOrbitals", ["featurize", "feature_labels"]), cls("matminer.featurizers.composition.thermo", "CohesiveEnergy", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.composition.alloy", "Miedema", ["__init__", "featurize", "feature_labels"])], "composition_dataframe_planned", ["seed_pypi_raw/matminer/src/matminer/featurizers/composition"]),
  C("structure_site_features", "结构和位点特征", "保留密度、对称性、径向分布、位点统计和局部环境等互补特征。", [cls("matminer.featurizers.structure.order", "DensityFeatures", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.structure.symmetry", "GlobalSymmetryFeatures", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.structure.rdf", "RadialDistributionFunction", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.structure.sites", "SiteStatsFingerprint", ["__init__", "fit", "featurize", "feature_labels", "from_preset"]), cls("matminer.featurizers.site.fingerprint", "AGNIFingerprints", ["__init__", "featurize", "feature_labels"]), cls("matminer.featurizers.site.chemical", "ChemicalSRO", ["from_preset", "fit", "featurize", "feature_labels"]), cls("matminer.featurizers.site.bonding", "BondOrientationalParameter", ["__init__", "featurize", "feature_labels"])], "structure_feature_fixture_planned", ["seed_pypi_raw/matminer/src/matminer/featurizers"]),
  C("featurizer_pipeline", "批量特征流水线", "BaseFeaturizer 和 MultipleFeaturizer 支持对 DataFrame 批量变换并检查特征标签。", [cls("matminer.featurizers.base", "BaseFeaturizer", ["set_n_jobs", "precheck_dataframe", "fit", "transform", "featurize_dataframe", "featurize_many", "featurize", "feature_labels"]), cls("matminer.featurizers.base", "MultipleFeaturizer", ["__init__", "featurize", "feature_labels", "fit", "featurize_many"]), cls("matminer.featurizers.conversions", "ConversionFeaturizer", ["__init__", "featurize_dataframe", "featurize", "feature_labels"])], "pipeline_fixture_planned", ["seed_pypi_raw/matminer/src/matminer/featurizers/base.py"]),
 ]},
"spglib_v2.7.0": {
 "profile_id": "spglib_symmetry_v1", "boundary": "晶体对称性、标准化晶胞和 k 点网格的核心 Python API；该分发公开调用少于目标范围，不为凑数加入底层或重复接口。", "target": (20, 40), "exception": {"desired_all_func": {"min": 50, "max": 100}, "target_exception_reason": "spglib 2.7.0 Python 层公开函数仅 31 个且主要由 C 扩展导出；保留全部可用核心接口，不虚构或重复扩展。"},
 "caps": [C("symmetry", "空间群和标准化晶胞", "标准化、对称操作、点群和数据库查询构成结构验证闭环。", [fn("spglib.cell", "standardize_cell"), fn("spglib.cell", "refine_cell"), fn("spglib.cell", "find_primitive"), fn("spglib.spg", "get_symmetry"), fn("spglib.spg", "get_symmetry_dataset"), fn("spglib.spg", "get_spacegroup"), fn("spglib.spg", "get_spacegroup_type"), fn("spglib.spg", "get_spacegroup_type_from_symmetry"), fn("spglib.spg", "get_symmetry_from_database"), fn("spglib.spg", "get_hall_number_from_symmetry"), fn("spglib._internal", "get_pointgroup"), fn("spglib._internal", "get_symmetry_layerdataset"), fn("spglib._internal", "get_layergroup"), fn("spglib.reduce", "delaunay_reduce"), fn("spglib.reduce", "niggli_reduce")], "known_structure_fixture", ["seed_pypi_raw/spglib/python/spglib"]), C("reciprocal_mesh", "倒空间网格和磁性对称性", "保留 irreducible reciprocal mesh、旋转映射及磁性空间群数据接口。", [fn("spglib.kpoints", "get_ir_reciprocal_mesh"), fn("spglib._internal", "get_stabilized_reciprocal_mesh"), fn("spglib._internal", "get_grid_point_from_address"), fn("spglib._internal", "get_grid_points_by_rotations"), fn("spglib._internal", "get_BZ_grid_points_by_rotations"), fn("spglib._internal", "relocate_BZ_grid_address"), fn("spglib.msg", "get_magnetic_symmetry"), fn("spglib.msg", "get_magnetic_symmetry_dataset"), fn("spglib.msg", "get_magnetic_spacegroup_type"), fn("spglib.msg", "get_magnetic_spacegroup_type_from_symmetry"), fn("spglib.msg", "get_magnetic_symmetry_from_database")], "reciprocal_fixture_planned", ["seed_pypi_raw/spglib/python/spglib"]) ]},
"jobflow_v0.3.1": {
 "profile_id": "jobflow_workflow_engine_v1", "boundary": "Job/Flow/Maker、引用解析、状态存储和本地运行；排除特定调度器的长尾适配。", "target": (50, 100),
 "caps": [C("job_flow", "作业和流程组合", "Job、Flow、Maker 形成输入—执行—输出—串联的核心工作流。", [cls("jobflow.core.job", "Job", ["__init__", "run", "resolve_args", "input_references", "input_uuids", "maker", "set_uuid", "update_kwargs", "update_metadata", "update_config", "as_dict"]), cls("jobflow.core.flow", "Flow", ["__init__", "jobs", "output", "job_uuids", "all_uuids", "graph", "iterflow", "update_kwargs", "append_name", "add_jobs", "remove_jobs"]), cls("jobflow.core.maker", "Maker", ["make", "name", "update_kwargs"]), fn("jobflow.core.flow", "get_flow"), fn("jobflow.managers.local", "run_locally")], "local_workflow_fixture_planned", ["seed_pypi_raw/jobflow/src/jobflow/core"]), C("references", "输出引用和参数解析", "OutputReference 与解析函数显式表达跨 Job 数据依赖，是多步任务可验证性的关键。", [cls("jobflow.core.reference", "OutputReference", ["__init__", "resolve", "set_uuid", "as_dict"]), fn("jobflow.core.reference", "resolve_references"), fn("jobflow.core.reference", "find_and_get_references"), fn("jobflow.core.reference", "find_and_resolve_references"), cls("jobflow.core.job", "Response", ["from_job_returns"]), fn("jobflow.core.job", "apply_schema")], "reference_resolution_planned", ["seed_pypi_raw/jobflow/src/jobflow/core/reference.py"]), C("store_state", "状态和持久化", "JobStore、JobConfig 与状态工具支持失败恢复和离线执行记录；JobConfig 构造由数据模型生成，静态索引不虚构构造方法。", [cls("jobflow.core.store", "JobStore", ["__init__", "connect", "close", "count", "query", "query_one", "update", "ensure_index", "groupby", "remove_docs", "get_output", "from_dict_spec"]), cls("jobflow.core.job", "JobConfig", []), cls("jobflow.core.state", "State", ["reset"]), fn("jobflow.utils.uid", "suid"), fn("jobflow.utils.uuid", "suuid"), fn("jobflow.utils.graph", "itergraph")], "in_memory_store_planned", ["seed_pypi_raw/jobflow/src/jobflow/core/store.py"]) ]},
"custodian_v2025.12.14": {
 "profile_id": "custodian_recovery_v1", "boundary": "通用 Custodian 运行监控、VASP/QC/CP2K 代表作业、错误处理和验证；不展开所有量化软件适配。", "target": (50, 100),
 "caps": [C("runner", "作业监控和重试", "Custodian、Job 生命周期和 VASP 代表作业覆盖外部计算的执行/恢复边界。", [cls("custodian.custodian", "Custodian", ["__init__", "from_spec", "run", "run_interrupted"]), cls("custodian.vasp.jobs", "VaspJob", ["__init__", "setup", "run", "postprocess", "double_relaxation_run", "metagga_opt_run", "full_opt_run", "terminate"]), cls("custodian.qchem.jobs", "QCJob", ["__init__", "setup", "run", "postprocess", "terminate", "opt_with_frequency_flattener"]), cls("custodian.cp2k.jobs", "Cp2kJob", ["__init__", "setup", "run", "postprocess", "terminate"])], "mock_process_planned", ["seed_pypi_raw/custodian/src/custodian"]), C("handlers", "错误处理和输入修复", "错误处理器、Modder 与验证器组成失败—修复—重试闭环。", [cls("custodian.vasp.handlers", "VaspErrorHandler", ["__init__", "check", "correct"]), cls("custodian.vasp.interpreter", "VaspModder", ["__init__", "apply_actions"]), cls("custodian.vasp.validators", "VasprunXMLValidator", ["__init__", "check"]), cls("custodian.qchem.handlers", "QChemErrorHandler", ["__init__", "check", "correct"]), cls("custodian.ansible.interpreter", "Modder", ["__init__", "modify", "modify_object"]), fn("custodian.vasp.io", "load_vasprun"), fn("custodian.vasp.utils", "increase_k_point_density")], "synthetic_error_fixture_planned", ["seed_pypi_raw/custodian/src/custodian/vasp"]), C("support", "备份和辅助流程", "保留通用备份和坐标扰动等可组合辅助。", [fn("custodian.utils", "backup"), fn("custodian.qchem.utils", "perturb_coordinates"), fn("custodian.cp2k.utils", "restart")], "filesystem_fixture_planned", ["seed_pypi_raw/custodian/src/custodian/utils.py"]) ]},
"phonopy_v4.5.0": {
 "profile_id": "phonopy_lattice_dynamics_v1", "boundary": "Phonopy 主对象、位移/力常数、网格、能带和热力学分析；排除 CLI 参数和各外部计算器的重复解析器。", "target": (50, 100),
 "caps": [C("phonon_core", "声子核心计算对象", "Phonopy 主对象和 load 接口覆盖结构、位移、力常数、网格和声子结果。", [cls("phonopy.api_phonopy", "Phonopy", ["__init__", "primitive", "unitcell", "supercell", "symmetry", "dataset", "displacements", "force_constants", "forces", "dynamical_matrix", "supercells_with_displacements", "mesh_numbers", "qpoints", "band_structure", "group_velocity", "mesh", "random_displacements", "dynamic_structure_factor"]), fn("phonopy.cui.load", "load"), fn("phonopy.file_IO", "write_FORCE_SETS"), fn("phonopy.harmonic.dynmat_to_fc", "get_commensurate_points")], "silicon_phonon_fixture_planned", ["seed_pypi_raw/phonopy/phonopy/api_phonopy.py"]), C("analysis", "声子能带、Grüneisen 和热力学", "保留高层分析对象的采样、读取和结果写出接口。", [cls("phonopy.api_gruneisen", "PhonopyGruneisen", ["__init__", "get_phonon", "set_mesh", "get_mesh", "set_band_structure", "get_band_structure", "write_yaml_mesh", "write_hdf5_mesh"]), cls("phonopy.api_qha", "PhonopyQHA", ["__init__", "bulk_modulus", "thermal_expansion", "helmholtz_volume", "volume_temperature", "gibbs_temperature", "heat_capacity_P_numerical", "get_bulk_modulus_parameters"]), cls("phonopy.phonon.group_velocity", "GroupVelocity", ["__init__", "run", "group_velocities"]), cls("phonopy.phonon.irreps", "IrReps", ["__init__", "get_projection_operators", "show", "write_yaml"]), fn("phonopy.phonon.degeneracy", "degenerate_sets"), fn("phonopy.phonon.grid", "length2mesh")], "analytic_fixture_planned", ["seed_pypi_raw/phonopy/phonopy/api_qha.py", "seed_pypi_raw/phonopy/phonopy/phonon"]), C("force_interfaces", "力数据和机器学习接口", "保留通用力读取/写出以及 MLP 训练接口的代表方法，不重复软件专用适配。", [cls("phonopy.interface.mlp", "PhonopyMLP", ["__init__", "save", "load", "evaluate", "develop", "develop_from_structures"]), cls("phonopy.interface.fc_calculator", "FDFCSolver", ["__init__", "force_constants"]), fn("phonopy.interface.vasp", "check_forces"), fn("phonopy.interface.calculator", "get_default_displacement_distance"), fn("phonopy.interface.lammps", "write_supercells_with_displacements")], "force_fixture_planned", ["seed_pypi_raw/phonopy/phonopy/interface"]) ]},
"phono3py_v4.5.0": {
 "profile_id": "phono3py_transport_v1", "boundary": "三阶力常数、散射、晶格热导率和结果读写核心对象；排除 CLI、四阶实验接口及重复格式辅助。", "target": (50, 100),
 "caps": [C("fc3_interaction", "三阶力常数和三声子相互作用", "FC3、位移数据和 Interaction 构成从力到散射的主链。", [cls("phono3py.phonon3.interaction", "Interaction", ["__init__", "run", "interaction_strength", "mesh_numbers", "fc3", "get_triplets_at_q", "get_phonons", "set_grid_point", "set_phonon_data", "run_phonon_solver"]), cls("phono3py.phonon3.collision_matrix", "CollisionMatrix", ["__init__", "run", "get_collision_matrix", "set_grid_point"]), fn("phono3py.phonon3.fc3", "get_fc3"), fn("phono3py.phonon3.dataset", "get_displacements_and_forces_fc3"), fn("phono3py.phonon3.triplets", "get_triplets_at_q"), fn("phono3py.interface.calculator", "get_default_displacement_distance")], "small_fc3_fixture_planned", ["seed_pypi_raw/phono3py/phono3py/phonon3"]), C("conductivity", "热导率和速度求解", "RTA/LBTE 求解器及群速度接口覆盖热输运主结果。", [cls("phono3py.conductivity.calculators", "ConductivityCalculatorBase", ["__init__", "run", "kappa_settings", "mesh_numbers", "frequencies", "qpoints", "temperatures", "gamma", "group_velocities", "mode_heat_capacities", "get_extra_kappa_output"]), cls("phono3py.conductivity.kappa_solvers", "RTAKappaSolver", ["__init__", "finalize", "kappa", "mode_kappa", "get_extra_kappa_output"]), cls("phono3py.conductivity.interband_kappa_solvers", "InterBandRTAKappaSolver", ["__init__", "finalize", "kappa", "kappa_intra", "kappa_inter"]), cls("phono3py.conductivity.velocity_solvers", "GroupVelocitySolver", ["__init__", "compute"]), fn("phono3py.conductivity.heat_capacity_solvers", "compute_bulk_mode_cv"), fn("phono3py.conductivity.utils", "get_mfp")], "transport_fixture_planned", ["seed_pypi_raw/phono3py/phono3py/conductivity"]), C("io_analysis", "输运数据和频率分析", "保留读写、联合态密度和自能分析的代表入口。", [cls("phono3py.phonon3.joint_dos", "JointDos", ["__init__", "run", "run_jdos", "joint_dos", "frequency_points", "get_phonons", "set_grid_point"]), cls("phono3py.phonon3.imag_self_energy", "ImagSelfEnergy", ["__init__", "run", "run_interaction", "imag_self_energy", "get_imag_self_energy", "set_grid_point", "set_sigma", "set_temperature"]), cls("phono3py.file_IO", "Phono3pyYaml", ["__init__", "dataset", "read"]), fn("phono3py.file_IO", "write_fc3_to_hdf5"), fn("phono3py.file_IO", "read_fc3_from_hdf5"), fn("phono3py.file_IO", "write_kappa_to_hdf5"), fn("phono3py.file_IO", "read_gamma_from_hdf5"), fn("phono3py.phonon.func", "gaussian")], "hdf5_fixture_planned", ["seed_pypi_raw/phono3py/phono3py/file_IO.py"]),
 ]},
"pygmsh_v7.1.17": {
 "profile_id": "pygmsh_geometry_mesh_v1", "boundary": "pygmsh 几何构造、布尔运算、物理分组和 meshio 导出；保留代表实体而不重复每种几何的同构构造器。", "target": (50, 100),
 "caps": [C("geometry_2d", "二维几何构造", "geo.Geometry 和 CommonGeometry 覆盖点线面、圆矩形和网格生成。", [cls("pygmsh.geo.geometry", "Geometry", ["__init__", "add_circle", "add_rectangle", "add_ellipsoid", "add_ball", "add_box", "add_polygon", "revolve", "twist", "in_surface", "in_volume"]), cls("pygmsh.common.geometry", "CommonGeometry", ["__init__", "add_point", "add_line", "add_circle_arc", "add_curve_loop", "add_plane_surface", "add_polygon", "add_physical", "set_mesh_size_callback", "generate_mesh", "save_geometry", "synchronize"]), fn("pygmsh.helpers", "write"), fn("pygmsh.helpers", "extract_to_meshio")], "gmsh_mesh_fixture_planned", ["seed_pypi_raw/pygmsh/src/pygmsh/geo", "seed_pypi_raw/pygmsh/src/pygmsh/common"]), C("geometry_3d", "三维 OCC 几何和布尔操作", "OCC Geometry 的实体、布尔和导入接口连接到 Gmsh 三维网格。", [cls("pygmsh.occ.geometry", "Geometry", ["__init__", "add_rectangle", "add_disk", "add_ball", "add_box", "add_cone", "add_cylinder", "add_ellipsoid", "add_torus", "add_wedge", "boolean_intersection", "boolean_union", "boolean_difference", "boolean_fragments", "import_shapes", "revolve"]), cls("pygmsh.occ.box", "Box", ["__init__"]), cls("pygmsh.occ.cylinder", "Cylinder", ["__init__"]), cls("pygmsh.occ.ball", "Ball", ["__init__"]), cls("pygmsh.occ.rectangle", "Rectangle", ["__init__"]), fn("pygmsh.helpers", "rotation_matrix"), fn("pygmsh.helpers", "orient_lines")], "occ_boolean_fixture_planned", ["seed_pypi_raw/pygmsh/src/pygmsh/occ"]),
 ]},
"scikit-fem_12.0.2": {
 "profile_id": "scikit_fem_pde_v1", "boundary": "二维/三维网格、有限元基、形式组装、边界条件、线性求解和 meshio 转换；不展开所有元素类型和绘图后端。", "target": (50, 100),
 "caps": [C("mesh_basis", "网格与有限元基", "Mesh、CellBasis、FacetBasis 和基自由度查询覆盖 PDE 离散化输入。", [cls("skfem.mesh.mesh", "Mesh", ["__init__", "with_boundaries", "with_subdomains", "boundary_nodes", "interior_nodes", "nodes_satisfying", "elements_satisfying", "is_valid", "save", "load", "to_dict", "from_dict", "copy", "refined", "scaled", "translated", "mirrored", "remove_elements", "remove_unused_nodes", "element_finder", "draw"]), cls("skfem.assembly.basis.cell_basis", "CellBasis", ["__init__", "get_dofs", "interpolate", "project", "with_element", "with_elements", "boundary", "probes"]), cls("skfem.assembly.basis.facet_basis", "FacetBasis", ["__init__", "get_dofs", "interpolate", "project", "trace"]), cls("skfem.assembly.dofs", "DofsView", ["flatten", "sort", "keep", "drop", "all", "nodal", "facet", "interior"])], "poisson_mesh_fixture_planned", ["seed_pypi_raw/scikit-fem/skfem/mesh", "seed_pypi_raw/scikit-fem/skfem/assembly"]), C("forms", "弱形式和矩阵组装", "BilinearForm/LinearForm、asm 和离散场 helper 构成可组合弱形式。", [cls("skfem.assembly.form.bilinear_form", "BilinearForm", ["assemble"]), cls("skfem.assembly.form.linear_form", "LinearForm", ["assemble"]), cls("skfem.assembly.form.coo_data", "COOData", ["tolocal", "fromlocal", "tocsr", "toarray", "solve", "astuple"]), fn("skfem.assembly", "asm"), fn("skfem.helpers", "grad"), fn("skfem.helpers", "dot"), fn("skfem.helpers", "div"), fn("skfem.helpers", "ddot"), fn("skfem.helpers", "inner")], "matrix_assembly_fixture_planned", ["seed_pypi_raw/scikit-fem/skfem/assembly", "seed_pypi_raw/scikit-fem/skfem/helpers.py"]), C("solve_io", "边界条件、求解和网格转换", "Poisson 模型、condense/enforce/solve 及 meshio 读写形成可验证 PDE 闭环。", [fn("skfem.models.poisson", "laplace"), fn("skfem.models.poisson", "unit_load"), fn("skfem.utils", "solve"), fn("skfem.utils", "solve_linear"), fn("skfem.utils", "condense"), fn("skfem.utils", "enforce"), fn("skfem.utils", "penalize"), fn("skfem.io.meshio", "from_meshio"), fn("skfem.io.meshio", "to_meshio"), fn("skfem.io.meshio", "from_file"), fn("skfem.io.meshio", "to_file"), fn("skfem.quadrature", "get_quadrature")], "poisson_solution_fixture_planned", ["seed_pypi_raw/scikit-fem/skfem/utils.py", "seed_pypi_raw/scikit-fem/skfem/io/meshio.py"]),
 ]},
}

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for stem, rule in RULES.items():
        raw_path = ROOT / f"{stem}.json"
        payload = json.loads(raw_path.read_text(encoding="utf-8"))
        seed = payload[0]
        available = {(t["module"], t["name"], t["type"]): t for t in seed["init_ref_tools"]}
        if stem == "custodian_v2025.12.14":
            rule["caps"][0]["symbols"] += [cls("custodian.custodian", "Job", ["setup", "run", "postprocess", "terminate", "name"]), cls("custodian.vasp.jobs", "VaspNEBJob", ["__init__", "setup", "run", "postprocess"]), cls("custodian.vasp.jobs", "GenerateVaspInputJob", ["__init__", "setup", "run", "postprocess"]), cls("custodian.vasp.validators", "VaspFilesValidator", ["__init__", "check"])]
        if stem == "pygmsh_v7.1.17":
            rule["caps"][0]["symbols"][1]["methods"] += ["add_surface", "add_surface_loop", "add_volume", "extrude"]
        symbols = []
        for cap in rule["caps"]:
            for spec in cap["symbols"]:
                if stem == "mp-api_v0.46.5" and spec["module"] == "mp_api.client.mprester" and spec["name"] == "MPRester":
                    spec["methods"] += ["get_database_version", "get_emmet_version", "get_material_id_references", "get_pourbaix_entries", "get_ion_entries", "get_wulff_shape", "get_charge_density_from_material_id", "get_stability"]
                if stem == "phonopy_v4.5.0" and spec["module"] == "phonopy.interface.fc_calculator" and spec["name"] == "FDFCSolver":
                    spec["module"] = "phonopy.harmonic.force_constants"
                if stem == "phono3py_v4.5.0" and spec["module"] == "phono3py.file_IO" and spec["name"] == "Phono3pyYaml":
                    spec["module"] = "phono3py.interface.phono3py_yaml"
                key = (spec["module"], spec["name"], spec["type"])
                if key not in available:
                    raise ValueError(f"{stem}: missing symbol {key}")
                if spec["type"] == "class":
                    methods = {m["name"]: m for m in available[key].get("function", [])}
                    missing = [m for m in spec.get("methods", []) if m not in methods]
                    if missing:
                        # Keep the authored boundary but materialize only methods
                        # directly present in this release's static index.
                        print(f"{stem}: omit unavailable methods {key}: {missing}")
                        spec["methods"] = [m for m in spec.get("methods", []) if m in methods]
                symbols.append(spec)
        # Add an explicit reason only where source documentation is empty.
        for spec in symbols:
            source = available[(spec["module"], spec["name"], spec["type"])]
            empty = not str(source.get("description") or "").strip()
            if spec["type"] == "class":
                chosen = set(spec.get("methods", []))
                empty = empty or any(m["name"] in chosen and not str(m.get("description") or "").strip() for m in source.get("function", []))
            if empty:
                spec["missing_description_reason"] = "该接口是所选能力闭环所需的公开入口；发布源码缺少独立说明，保留原空字段，不补造描述，也不表示运行已验证。"
        profile = {"profile_id": rule["profile_id"], "package": seed["environment"]["basic_info"]["name"], "version": seed["environment"]["basic_info"]["version"], "source_sha256": _canonical_sha256(payload), "boundary": rule["boundary"], "target_all_func": {"min": rule["target"][0], "max": rule["target"][1]}, "capabilities": rule["caps"]}
        if "exception" in rule:
            profile.update(rule["exception"])
        out = OUT / f"{stem}.json"
        out.write_text(json.dumps(profile, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(out, len(symbols))

if __name__ == "__main__":
    main()
