"""Joint cocotb/UVM/AXI selections from real simulator-backed tasks."""
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_design_lab_sources import BASE,RAW


def co(module,name,methods,cap,why,construction=None):
    return symbol('cocotb',module,name,methods,cap,why,construction)


def uv(module,name,methods,cap,why,construction=None):
    return symbol('pyuvm','pyuvm.'+module,name,methods,cap,why,construction)


def ax(name,methods,cap,why,construction=None):
    return symbol('cocotbext-axi','cocotbext.axi.axis',name,methods,cap,why,construction)


def common():
    result=[co('cocotb_tools.runner','get_runner',None,'execute','选择真实Icarus后端，runner仅调度不计算DUT。'),co('cocotb_tools.runner','Runner','build test','execute','明确源码/顶层/输出目录编译和执行，删除rm_build_folder等宽泛删除动作。','get_runner返回Icarus子类，继承Runner.build/test。'),co('cocotb.handle','ValueObjectBase','get set','signal','统一DUT句柄值读写，value属性是同一能力不重复计数。','由仿真器dut属性访问提供句柄，不自行构造。'),co('cocotb._gpi_triggers','Timer','__init__','timing','有限仿真时间等待。'),co('cocotb._gpi_triggers','ReadOnly',[],'timing','等待HDL当前时间片稳定采样。','Singleton派生GPITrigger，正常ReadOnly()；源类无显式__init__。'),co('cocotb.clock','Clock','__init__ start stop cycles','timing','明确周期/单位的实际仿真时钟。')]
    # High-level public functions are defined in private-named implementation modules.
    result += [co('cocotb._extended_awaitables','with_timeout',None,'timing','有限等待事务，避免无界阻塞。'),co('cocotb._test','start_soon',None,'execute','调度并发协程；实际导出模块以候选索引为准。')]
    return result


def main():
    c=Collection(base=BASE,raw=RAW)
    # Resolve exact source modules once; public re-export names are never copied.
    import json
    raw=json.loads((RAW/'cocotb_v2.1.0.json').read_text(encoding='utf-8'))[0]['init_ref_tools']
    fun={name:next(t['module'] for t in raw if t['type']=='function' and t['name']==name) for name in ['start_soon','with_timeout']}
    cocotb=common()
    for item in cocotb:
        if item['name'] in fun:item['module']=fun[item['name']]
    source_test=c.source('https://docs.cocotb.org/en/v2.1.0/writing_testbenches.html','官方2.1.0正文区分句柄与value、位宽范围、@test和真正assert；日志error本身不令测试失败。',['DUT','signal_value','stimulus','assertion'],['ValueObjectBase.get','ValueObjectBase.set','test'],['固定输入结果表定位缺失操作数/进位截断'])
    source_time=c.source('https://docs.cocotb.org/en/v2.1.0/timing_model.html','官方时序模型指出RisingEdge返回时下游HDL尚未反应，ReadOnly在时间片末稳定；当前例Timer后ReadOnly采样，写下一值前推进时间。',['time_step','settled_value','trigger'],['Timer','ReadOnly','Clock'],['避免采样竞态导致伪失败'])
    source_run=c.source('https://docs.cocotb.org/en/v2.1.0/library_reference.html','官方API给出get_runner/Runner.build/test用于真实编译测试，并说明runner API仍experimental；不能用构建配置代替仿真结果。',['source','top_module','test_module','results_xml'],['get_runner','Runner.build','Runner.test'],['实际Icarus构建及xUnit结果核对'])
    for sid in ['03.06.01','03.06.02','03.07.01']:
        syms=list(cocotb)
        d=dict(scenario_id=sid,sources=[source_test,source_time,source_run],entities=[dict(name='hardware_design',identity='source_revision+top_module',attributes=['ports','widths','fault_controls','clock','reset'],lifecycle='load fixed SV -> Icarus compile -> manipulate explicit inputs -> observe actual HDL。'),dict(name='verification_run',identity='run_id',attributes=['fixed_stimuli','expected_results','observations','failures','XML/log'],lifecycle='initialise -> run normal -> expose wrong state -> repair -> same oracle；每个suite由cocotb注册执行。')],capabilities=['execute','signal','timing'],symbols=syms,bridges=[],runtime_infrastructure=[dict(reference='IcarusVerilog12.0',kind='external_runtime',reason='WSL用户私有解包iverilog/vvp，真实cocotb GPI扩展连接；固定verification_dut.sv由源码编译。'),dict(reference='fixed_hardware_oracles',kind='infrastructure',reason='4组加法手写结果表或5字节AXI帧；不改变目标来通过错误设计。'),dict(reference='cocotb_public_reexports',kind='public_alias_map',reason='公开cocotb.triggers等重导出源定义于_gpi_triggers/_base_triggers等模块，保留唯一源定义；dut.value访问对应源ValueObjectBase。')],boundaries=['仅固定小型DUT的真实事件仿真，非完整芯片、门级时序或覆盖率签核。','参考API未逐项实跑；runner API在官方标为experimental，后续facade需固定版本。'],runtime_report=(BASE/f'runtime/cocotb/{sid}.json').as_posix(),runtime_scope='cocotb2.1.0连接真实Icarus12.0；XML三套suite零错误/零失败，每场景两个正常/错误/修复任务。')
        if sid=='03.06.01':
            d['description']='以cocotb控制实际HDL仿真：编译固定DUT、驱动信号、等待稳定后采样，与独立结果表比较；定位缺失操作数或进位截断并修复控制状态，保留测试日志及执行工件。'
            d['packages']=[('cocotb','primary','统一信号、调度、触发器和仿真后端入口，不加入UVM/协议对象增加简单功能任务负担。')]
            syms += [co('cocotb.task','Task','cancel cancelled done result exception get_name','execute','并发任务检查与受控取消，排除弃用kill/join。','由start_soon返回真实Task。'),co('cocotb.queue','Queue','__init__','execute','协程生产消费队列。'),co('cocotb.queue','AbstractQueue','qsize empty full put put_nowait get get_nowait','execute','Queue继承的等待/状态读写，避免复制到子类。','通过Queue构造获得。'),co('cocotb._base_triggers','Event','__init__ set wait clear is_set','timing','显式事件同步，data/name为状态。'),co('cocotb._base_triggers','Lock','__init__ locked acquire release','timing','多协程共享资源同步。'),co('cocotb.types._logic_array','LogicArray','__init__ from_unsigned from_signed from_bytes to_unsigned to_signed to_bytes resolve','signal','明确位宽/符号/未知位处理，剔除弃用integer/binstr别名。'),co('cocotb.types._range','Range','__init__ from_range to_range index','signal','HDL位索引方向与Python范围互转。')]
            for name in ['RisingEdge','FallingEdge','ValueChange','ReadWrite','NextTimeStep']:
                syms.append(co('cocotb._gpi_triggers',name,[],'timing','常用仿真阶段或信号边沿触发，原生调度返回。','构造由继承/元类处理，源类无独立__init__；按公开'+name+'(...)使用。'))
            for name in ['Combine','First','ClockCycles']:
                syms.append(co('cocotb._extended_awaitables',name,'__init__','timing','常用组合等待：全部完成、任一完成或有限周期，补足并发任务完成条件。'))
            d['tasks']=[recipe('repair_functional_operand_path','用四组固定输入驱动实际DUT，发现drop_b导致第二操作数漏算；恢复控制状态并按同表采样复验。','expected=[0,3,256,510]固定，错误输出[0,1,255,255]。',[('编译并执行',['cocotb_tools.runner.get_runner','cocotb_tools.runner.Runner.build','cocotb_tools.runner.Runner.test']),('驱动与稳定采样',['cocotb.handle.ValueObjectBase.set','cocotb._gpi_triggers.Timer.__init__','cocotb._gpi_triggers.ReadOnly','cocotb.handle.ValueObjectBase.get']),('修复控制重跑',['cocotb.handle.ValueObjectBase.set','cocotb.handle.ValueObjectBase.get'])],['错误输出与目标不同','修复四点匹配手写表'],'test_hardware_verification.py:functional operand'),recipe('repair_functional_carry_path','发现truncate_carry使255+1和255+255分别变0和254；恢复9bit路径后真实DUT输出256和510。','不能修改oracle或只保留无溢出输入。',[('驱动溢出输入',['cocotb.handle.ValueObjectBase.set']),('稳定采样并比较',['cocotb._gpi_triggers.Timer.__init__','cocotb._gpi_triggers.ReadOnly','cocotb.handle.ValueObjectBase.get']),('修复并重验',['cocotb.handle.ValueObjectBase.set','cocotb.handle.ValueObjectBase.get'])],['错误[0,3,0,254]','修复[0,3,256,510]'],'test_hardware_verification.py:functional carry')]
        elif sid=='03.06.02':
            d['description']='在cocotb真实仿真上构建pyuvm事务环境：sequence/sequencer驱动DUT，analysis端口将观察结果交scoreboard；以固定四事务集合同时检查功能与覆盖完整性，修复错误路径或漏发事务。'
            d['packages']=[('pyuvm','primary','高层组件、phase、sequence和事务检查负责环境组织。'),('cocotb','complement','提供真实HDL执行、信号与时间语义，无第二套结果计算。')]
            d['sources'] += [c.source('https://github.com/pyuvm/pyuvm/tree/5.0.0','官方正文解释common phases、factory、ConfigDB和sequence，并示例TinyALU结果检查；UVM对象模型为cocotb补充层。',['environment','component','sequence','config'],['uvm_root.run_test','ConfigDB','uvm_sequence'],['事务数不足和功能错误分别定位']),c.source('https://github.com/pyuvm/pyuvm/blob/5.0.0/examples/TinyALU/testbench.py','官方TinyALU例通过seq_item_port.get_next_item/item_done驱动，analysis_port.write交scoreboard，connect_phase连接TLM，run_phase raise/drop objection控制生命周期。',['sequencer','driver','analysis_port','scoreboard'],['uvm_sequence.start','uvm_seq_item_port.get_next_item','uvm_analysis_port.write'],['固定事务通过实际DUT再比较结果']),c.source('https://github.com/pyuvm/pyuvm/blob/5.0.0/examples/SimpleMem/testbench.py','官方SimpleMem示例区分ACTIVE/PASSIVE agent，固定覆盖前缀防止随机漏命中，独立scoreboard与coverage判断功能和测试覆盖。',['coverage','transaction','agent_mode'],['uvm_subscriber.write','ConfigDB'],['三事务都算对仍因漏第四事务被拒绝'])]
            d['capabilities']+=['component','transaction','scoreboard']
            syms += [uv('_s13_uvm_component','uvm_root','__init__ run_test find_all find','component','创建与运行新组件树并查找对象。'),uv('_s13_uvm_component','uvm_component','__init__ create get_parent get_full_name get_children get_child has_child raise_objection drop_objection build_phase connect_phase run_phase check_phase report_phase final_phase','component','公共组件协议和常用phase，剔除日志管理和重复层次别名。'),uv('_s13_uvm_component','ConfigDB','__init__ set get exists clear','component','事务数/模式配置存取与隔离。'),uv('_s14_15_python_sequences','uvm_sequence_item','__init__ set_context','transaction','携带输入字段的事务基类。'),uv('_s14_15_python_sequences','uvm_sequence','__init__ body start start_item finish_item get_response','transaction','序列生命周期与sequencer握手。'),uv('_s14_15_python_sequences','uvm_sequencer','__init__','transaction','请求仲裁对象，由sequence/driver高层接口操作。'),uv('_s14_15_python_sequences','uvm_seq_item_port','connect get_next_item try_next_item item_done get_response','transaction','driver连接和完成握手，避免重复调用内部put_req。','uvm_driver.__init__自动创建seq_item_port。'),uv('_s13_predefined_component_classes','uvm_driver','__init__','transaction','事务驱动组件。'),uv('_s13_predefined_component_classes','uvm_subscriber','__init__ write','scoreboard','analysis接收者与固定oracle检查。'),uv('_s12_uvm_tlm_interfaces','uvm_analysis_port','__init__ connect write','scoreboard','观察值广播与连接。'),uv('_s13_predefined_component_classes','uvm_env',[],'component','组成driver/sequencer/scoreboard的环境。','继承已保留uvm_component.__init__；源类无独立构造。'),uv('_s13_predefined_component_classes','uvm_test','__init__','component','顶层测试入口，固定实现由uvm_root.run_test调用。')]
            d['bridges']=[dict(**{'from':'pyuvm sequence/driver','to':'cocotb DUT signals','tool':'uvm_seq_item_port.get_next_item + ValueObjectBase.set/get + uvm_analysis_port.write'},contract='一次请求对应一次真实稳定采样；item_done在采样后，四组输入/输出和事务数同时验收。')]
            d['boundaries']+=['固定例观察由driver真实采样后analysis端口发布，未宣称另有独立monitor或完整UVM寄存器层验证。']
            refs=['pyuvm._s13_uvm_component.uvm_root.run_test','pyuvm._s13_uvm_component.ConfigDB.set','pyuvm._s14_15_python_sequences.uvm_sequence.start','pyuvm._s14_15_python_sequences.uvm_sequence.start_item','pyuvm._s14_15_python_sequences.uvm_sequence.finish_item','pyuvm._s14_15_python_sequences.uvm_seq_item_port.get_next_item','pyuvm._s14_15_python_sequences.uvm_seq_item_port.item_done','pyuvm._s12_uvm_tlm_interfaces.uvm_analysis_port.write']
            d['tasks']=[recipe('repair_uvm_observed_function','由sequence发出四事务，经driver真实DUT采样；scoreboard发现漏b输出，恢复硬件控制后重建UVM树按同表复验。','固定4事务和手写输出表；不同run_test隔离配置/组件。',[('构建组件连接并发事务',refs),('采样传递结果',['cocotb.handle.ValueObjectBase.get','pyuvm._s12_uvm_tlm_interfaces.uvm_analysis_port.write','pyuvm._s13_predefined_component_classes.uvm_subscriber.write']),('修复后重建重跑',['pyuvm._s13_uvm_component.uvm_root.run_test'])],['normal覆盖和结果均通过','drop_b后functional_match=False','修复四事务均正确'],'test_hardware_verification.py:uvm function'),recipe('repair_uvm_sequence_coverage','发现vector_count=3虽已发事务均算对却漏最后一条；将配置恢复4，新run_test同时通过输入集合和输出表。','expected四事务保持，不能削减覆盖目标。',[('读取并设置事务数',['pyuvm._s13_uvm_component.ConfigDB.get','pyuvm._s13_uvm_component.ConfigDB.set']),('执行并接收',refs),('修复配置重跑',['pyuvm._s13_uvm_component.uvm_root.run_test'])],['错误仅3事务且coverage_complete=False','修复4事务','完整输出[0,3,256,510]'],'test_hardware_verification.py:uvm coverage')]
        else:
            d['description']='围绕cocotbext-axi的AXI-Stream事务、背压与监视器构建协议环境，由cocotb驱动真实HDL stream桥；以固定帧检查数据损坏和长期ready阻塞，修复后保持顺序与完整性。'
            d['packages']=[('cocotbext-axi','primary','专用协议总线/source/sink/monitor为高层操作。'),('cocotb','complement','真实仿真时间、信号与后端执行。'),('cocotb-bus','complement','AxiStreamBus继承Bus的真实信号映射基础设施；只保留必要基础构造/采集，无重复通用driver/scoreboard。')]
            d['sources'] += [c.source('https://github.com/alexforencich/cocotbext-axi/tree/v0.1.28','官方说明AXI/AXI-Lite/APB主从及AXI-Stream Frame/Source/Sink/Monitor；from_prefix将DUT信号映射为bus，专用事务支持等待和背压。',['stream_bus','frame','queue','backpressure'],['AxiStreamBus.from_prefix','AxiStreamSource.send','AxiStreamMonitor.recv'],['固定帧损坏/阻塞修复']),c.source('https://github.com/alexforencich/cocotbext-axi/blob/v0.1.28/tests/axis/test_axis.py','官方测试构造source/sink/monitor并分别注入source idle与sink backpressure，核对frame tdata和monitor一致性。',['source','sink','monitor','pause_pattern'],['AxiStreamPause.set_pause_generator','AxiStreamMonitor.recv','AxiStreamBase.empty'],['下游背压期间保留帧，恢复ready后交付']),c.source('https://github.com/cocotb/cocotb-bus/tree/v0.3.0','官方将包定位为可复用bus接口与testbench基础设施；当前由专用AXI模型复用，不另加同类通用动作。',['signal_bundle','bus_prefix'],['Bus'],['正确命名前缀连接真实DUT'])]
            d['capabilities']+=['protocol','observe']
            syms += [ax('AxiStreamFrame','__init__ normalize compact','protocol','固定帧数据和sideband规范化，剔除内部tx完成回调。'),ax('AxiStreamBus','__init__ from_entity from_prefix','protocol','真实DUT信号映射。'),ax('AxiStreamBase','count empty clear','observe','继承队列状态与任务重置入口。','由source/sink/monitor构造获得，不单独使用抽象基类。'),ax('AxiStreamPause','set_pause_generator clear_pause_generator','protocol','背压/空闲生成器控制，pause属性保留为状态。','source/sink继承的mix-in，已保留具体构造。'),ax('AxiStreamSource','__init__ send send_nowait full idle wait','protocol','发送帧和等待队列排空，不重复write字节别名。'),ax('AxiStreamMonitor','__init__ recv recv_nowait idle wait','observe','真实被动帧观察及sink继承接收入口。'),ax('AxiStreamSink','__init__ full','protocol','主动ready背压接收器。'),symbol('cocotb-bus','cocotb_bus.bus','Bus','__init__ drive capture sample','protocol','专用AXI总线继承的基础映射/采样，不加入重复通用driver。')]
            d['count_exception']='固定AXI-Stream闭环使用专用帧/队列/背压/观察接口，若少于50不添加未运行的AXI-MM/APB全套方法凑数。'
            d['bridges']=[dict(**{'from':'AXI-Stream source/sink/monitor','to':'cocotb-bus -> cocotb GPI -> Icarus SV','tool':'AxiStreamBus.from_prefix + AxiStreamSource.send + AxiStreamMonitor.recv'},contract='同一8bit数据/valid-ready/tlast；背压时不消费，恢复时收到原五字节，monitor与sink一致。')]
            d['boundaries']+=['固定例真实运行AXI-Stream，未运行AXI memory-mapped突发、APB或CDC，不将包宽泛能力当验证证据。','axi0.1.28内部使用cocotb弃用setimmediatevalue/Edge/Task.kill产生DeprecationWarning，固定2.1.0实际兼容运行；不修改固定官方源码。']
            commonrefs=['cocotbext.axi.axis.AxiStreamBus.from_prefix','cocotbext.axi.axis.AxiStreamSource.__init__','cocotbext.axi.axis.AxiStreamSink.__init__','cocotbext.axi.axis.AxiStreamMonitor.__init__']
            d['tasks']=[recipe('repair_axis_data_corruption','以[0,1,127,128,255]发送固定帧并周期背压，错误数据路径异或1导致字节损坏；恢复数据路径后source/sink/monitor均核对原帧。','5字节不变，sink pause=[1,1,0,0]。',[('连接真实总线',commonrefs),('注入背压并发送',['cocotbext.axi.axis.AxiStreamPause.set_pause_generator','cocotbext.axi.axis.AxiStreamFrame.__init__','cocotbext.axi.axis.AxiStreamSource.send']),('观察并修复',['cocotbext.axi.axis.AxiStreamMonitor.recv','cocotb.handle.ValueObjectBase.set'])],['错误[1,0,126,129,254]','修复原5字节','sink与monitor一致'],'test_hardware_verification.py:axis corruption'),recipe('repair_axis_stalled_handshake','将ready桥阻塞200ns，确认source pending且sink/monitor没有帧；解除阻塞后限时接收原五字节并等待source排空。','保持已排队的原帧，不清队列绕过阻塞。',[('连接和排队',commonrefs+['cocotbext.axi.axis.AxiStreamSource.send']),('检查阻塞状态',['cocotb._gpi_triggers.Timer.__init__','cocotbext.axi.axis.AxiStreamSource.idle','cocotbext.axi.axis.AxiStreamBase.empty']),('恢复ready并限时完成',['cocotb.handle.ValueObjectBase.set','cocotbext.axi.axis.AxiStreamMonitor.recv','cocotbext.axi.axis.AxiStreamSource.wait'])],['200ns内0已收帧且source非idle','恢复收到原5字节','source最终idle'],'test_hardware_verification.py:axis handshake')]
        c.write(d)


if __name__=='__main__':
    main()
