"""Reviewed joint selections for the remaining eight microscopy scenes."""
from pathlib import Path
from seed_gen.scripts.scenario_collection_support import Collection, symbol, recipe

BASE=Path('seed_gen/scenario_collection/l1_metrology_quality')
RAW=Path('seed_gen/pypi_outputs/ori_all_funcs/scenario_collection/l1_metrology_quality')

def cl(p,m,n,methods,cap,why,construction=None):
    return symbol(p,m,n,methods,cap,why,construction)

def fn(p,m,names,cap,why):
    return [symbol(p,m,n,None,cap,why) for n in names.split()]

def signal_base(methods='data metadata original_metadata save deepcopy crop rebin sum mean change_dtype'):
    return cl('HyperSpy','hyperspy.signal','BaseSignal',methods,'signal','共享数组、原始元数据、无损副本、裁剪和持久化由HyperSpy提供；领域算法不复制。','通过具体Signal2D或领域信号继承，不额外构造一份基础信号。')

def libertem_symbols(raw=False):
    selected=[cl('LiberTEM','libertem.api','Context','__init__ load create_mask_analysis create_com_analysis create_radial_fourier_analysis create_disk_analysis create_ring_analysis create_point_analysis create_sum_analysis create_pick_analysis run run_udf run_udf_iter map close export_dataset','execution','单一会话负责载入、ROI、虚拟探测/归约和结果导出；固定验证使用Inline本地执行，非集群性能。'),
      cl('LiberTEM','libertem.executor.inline','InlineJobExecutor','__init__ get_available_workers','execution','明确本地执行器生命周期，避免把Dask集群部署加入最小环境。'),
      cl('LiberTEM','libertem.io.dataset.base.dataset','DataSet','get_num_partitions get_slices dtype shape check_valid diagnostics get_diagnostics roi get_supported_extensions get_correction_data supports_correction','dataset','文件形状、分块、校正与诊断合同；由具体读取器返回。','Context.load返回MemoryDataSet或RawFileDataSet子类。'),
      cl('LiberTEM','libertem.io.dataset.memory','MemoryDataSet','__init__ initialize check_valid get_num_partitions get_cache_key','dataset','可固定内存输入，与文件分块结果对照。'),
      cl('LiberTEM','libertem.udf.base','UDF','__init__ with_mask get_results','reduce','SumSigUDF等继承构造和结果接口；不暴露worker调度/内部缓冲配置。'),
      cl('LiberTEM','libertem.udf.sum','SumUDF','__init__ get_result_buffers','reduce','沿导航轴得到总衍射图；process_tile是实现细节，不作为外部动作。'),
      cl('LiberTEM','libertem.udf.sumsigudf','SumSigUDF','get_result_buffers','reduce','沿探测器轴得到扫描图，构造继承UDF。','继承UDF.__init__；Context.run_udf调用处理内部tile。'),
      cl('LiberTEM','libertem.common.buffers','BufferWrapper','shape data dtype raw_data valid_mask masked_data export','result','读取由UDF返回的形状、掩码、原值和导出；不允许直接伪造分析缓冲区。','Context.run_udf结果字典返回，不独立构造。')]
    if raw:
        selected.append(cl('LiberTEM','libertem.io.dataset.raw','RawFileDataSet','__init__ initialize get_diagnostics dtype shape check_valid get_cache_key','dataset','固定RAW入口显式大小端/类型/探测器和导航形状。'))
    return selected

def main():
    c=Collection(base=BASE,raw=RAW)
    L='https://libertem.github.io/LiberTEM/'; A='https://atomap.org/'
    K='https://kikuchipy.org/en/stable/tutorials/'; P='https://pyxem.readthedocs.io/en/stable/examples/processing/'
    B='https://abtem.readthedocs.io/en/latest/user_guide/walkthrough/'
    Y='https://py4dstem.readthedocs.io/en/latest/'
    evidence={
      L+'api.html':'官方Context示例从MIB读取器载入数据并创建圆盘虚拟探测分析；会话持有执行器和数据集，退出需要释放资源。',
      L+'udf.html':'UDF把探测器数据分块送入计算并合并结果，结果形状必须区分导航与信号维；不能从小样例推断集群吞吐。',
      L+'udf/basic.html':'基本UDF分别提供SumUDF导航归约和SumSigUDF探测器归约，声明结果缓冲区的轴含义是可验证任务的依据。',
      L+'reference/api.html':'官方API列出Context.load/run_udf/ROI及执行资源入口；固定tag源码为最终签名依据，开发版文档可能领先。',
      A+'finding_atom_lattices.html':'原子分辨图像示例按feature separation找峰，构建Sublattice并查近邻，再以质心和二维Gaussian精化，最后构造zone axes。',
      A+'analysing_atom_lattices.html':'实际双子晶格示例计算原子间距、椭圆率及属性图；图像像素和标定单位必须一起保留。',
      A+'quantification.html':'ADF原子列定量区分Voronoi/Watershed积分和Gaussian统计模型；绝对强度需要束流/探测器响应，位置样例不证明原子计数。',
      K+'pattern_processing.html':'镍EBSD背景处理说明inplace=False保留原信号；静态背景校正后按dtype强度范围重缩放，不应宣称绝对计数守恒。',
      K+'feature_maps.html':'图样质量和邻域相似度图在无需晶体索引时也能给出空间特征；不能将质量值直接当作物相标签。',
      K+'pattern_matching.html':'实际镍master-pattern工作流由取向网格字典、NCC匹配到取向/投影中心精化；图样和旋转元数据须同一行绑定。',
      'https://orix.readthedocs.io/en/stable/tutorials/crystal_map.html':'双相钢EBSD例子用CrystalMap、Phase与Rotation保存坐标、取向和物相，地图单元身份与匹配字典索引分开。',
      P+'centering_the_zero_beam.html':'逐图确定直射束位置再中心化，返回位移以xy表示，数组索引顺序不能照搬。',
      P+'azimuthal_integration.html':'电子衍射在标定中心/尺度后作方位积分；pyxem主实现覆盖此场景，避免再加入重叠pyFAI动作。',
      P+'calibrating_recip_space.html':'金光栅数据和已知晶格参考校准倒易/实空间尺度，必须记录加速电压、标样和单位；制造束中心不替代真实晶格标定。',
      B+'wave_functions.html':'平面波振幅和能量eV、extent Angstrom以及sampling=extent/gpts定义固定波场状态。',
      B+'potentials.html':'IAM将原子势叠加成样品势，忽略价电子成键影响；本次制造常量投影势不声称IAM材料精度。',
      B+'multislice.html':'多片公式exp(i sigma V)与Fresnel传播提供独立解析常相位样例的依据，分片厚度和投影势单位需明确。',
      Y+'api/classes.html':'DataCube轴为Rx/Ry/Qx/Qy；Calibration定义实/倒易像素尺度及原点，虚拟探测输出应保留原始采样引用。',
      Y+'examples.html':'官方入门以模拟Au纳米片HDF5载入并选导航位置画衍射图，给出多数据块身份及后续分析路径；在线示例不作为固定0.14.8可直接运行证明。',
      'https://github.com/py4dstem/py4DSTEM':'官方解释每扫描点记录二维衍射图，按实空间/衍射空间归约得到衍射图/虚拟图，并明确0.14.9相位检索重大改名；当前选0.14.8正式Release不混新接口。',
    }
    def src(urls):
        return [c.source(u,evidence[u],['scan','detector','axis_calibration','derived_signal','model'],['load','configure','reduce','calibrate','analyze','persist'],['固定像素/坐标和物理公式的分析与故障修复']) for u in urls]
    def task(sid,tid,desc,initial,steps,checks):
        return recipe(tid,desc,initial,steps,checks,'verify_diffraction.py:'+sid)
    designs=[]
    for sid,raw in [('07.01.03',False),('07.02.04',True)]:
        if raw:
            tasks=[task(sid,'process_raw_detector_partitions','以明确<f4的3072字节RAW为输入，三分块求和与单分块内存路径及独立NumPy和相等，总计294528。','4×3×8×8 arange制造数据，字节数、导航和信号形状均固定。',[('按配置加载并运行',['libertem.api.Context.__init__','libertem.executor.inline.InlineJobExecutor.__init__','libertem.api.Context.load','libertem.udf.sum.SumUDF.__init__','libertem.api.Context.run_udf']),('读取结果并关闭',['libertem.common.buffers.BufferWrapper.data','libertem.api.Context.close'])],['三分块与单分块一致','总计294528']),
              task(sid,'repair_raw_data_endianness','把错误>f4恢复为文件真实<f4；固定版本明确拒绝浮点字节交换，修复后12个位置强度须等于独立逐帧求和。','同一文件不可重写为迎合错误解码；错误配置保留诊断。',[('重加载真实dtype并归约',['libertem.api.Context.load','libertem.udf.base.UDF.__init__','libertem.api.Context.run_udf']),('检查返回值',['libertem.common.buffers.BufferWrapper.data'])],['记录NotImplementedError: byte swapping for floats not implemented yet','恢复原文件的正确逐位置计数'])]
        else:
            tasks=[task(sid,'reduce_partitioned_stem_data','对2×3×8×8 arange数据两分块运行导航/探测器轴归约，分别得到8×8衍射和与2×3扫描图，总计73536。','固定384个float32数；Inline执行器，不开启外部集群。',[('创建会话并载入',['libertem.api.Context.__init__','libertem.executor.inline.InlineJobExecutor.__init__','libertem.api.Context.load']),('运行两个归约',['libertem.udf.sum.SumUDF.__init__','libertem.udf.base.UDF.__init__','libertem.api.Context.run_udf','libertem.common.buffers.BufferWrapper.data']),('释放会话',['libertem.api.Context.close'])],['每位置2016/6112/10208/14304/18400/22496','总计73536']),
              task(sid,'repair_navigation_roi_mask','固定仅[0,0]/[1,2]有效的导航ROI，反掩码总计49024必须拒绝；恢复原ROI为24512。','原始数据不改，只修复选择状态。',[('带ROI重新归约',['libertem.api.Context.run_udf','libertem.common.buffers.BufferWrapper.data'])],['ROI形状为2×3而非8×8','恢复独立两帧和24512'])]
        designs.append(dict(scenario_id=sid,description=('将RAW文件、字节序、数据类型、导航/探测器形状、分块和执行会话组成可追溯的显微高通量处理环境；LiberTEM统一读取/分块/归约，结果需与独立和及内存路径一致。' if raw else '以LiberTEM统一大规模显微数据的分块、ROI、虚拟探测和归约生命周期；导航与探测器轴、掩码和执行器作为显式状态，小样例验证分块语义与错误ROI修复。'),packages=[('LiberTEM','primary','统一数据集与UDF执行，不为同一归约重复加入HyperSpy/py4DSTEM；其他场景通过明确数组和轴元数据边界交换。')],symbols=libertem_symbols(raw),sources=src([L+'api.html',L+'udf.html',L+'udf/basic.html',L+'reference/api.html']),tasks=tasks,
          entity_attributes=['raw_path','byte_order','dtype','nav_shape','sig_shape','partition_count','roi','executor','buffer_valid_mask'],
          bridge_contract='Context.load→DataSet→Context.run_udf→BufferWrapper；nav=(Ry,Rx)、sig=(Qy,Qx)由具体读取器记录，ROI只落导航维；关闭会话后不保留可执行资源。'))
    designs.append(dict(scenario_id='07.02.02',description='由HyperSpy承载原子分辨图像和轴，Atomap负责找峰、子晶格、近邻与原子列精化/几何图；保留像素尺度、峰间隔、原始图和位置历史，独立固定亚像素中心验证定位及错误峰间隔修复。',packages=[('atomap','primary','原子列和子晶格分析主实现。'),('HyperSpy','complement','图像/轴/元数据和持久化容器，避免复制另一套原子峰检测。')],
      symbols=fn('atomap','atomap.atom_finding_refining','get_atom_positions get_feature_separation','detect','初步峰位与最小间隔诊断。')+[
        cl('atomap','atomap.sublattice','Sublattice','__init__ atom_positions x_position y_position sigma_x sigma_y sigma_average atom_amplitude_gaussian2d rotation ellipticity signal find_nearest_neighbors refine_atom_positions_using_2d_gaussian refine_atom_positions_using_center_of_mass get_nearest_neighbor_directions construct_zone_axes get_atom_distance_list_from_zone_vector get_monolayer_distance_list_from_zone_vector get_atom_distance_difference_from_zone_vector get_atom_angles_from_zone_vector get_property_map get_ellipticity_map get_monolayer_distance_map get_atom_distance_map get_atom_distance_difference_map get_model_image get_position_history integrate_column_intensity set_scale set_element_info','lattice','裁剪为检测后精化、子晶格几何与量纲化属性，排除GUI手工编辑和重复绘图。'),
        cl('atomap','atomap.atom_lattice','Atom_Lattice','__init__ x_position y_position signal get_sublattice set_scale save','lattice','组合子晶格、原始信号和持久化；未验证原子化学计数。'),
        cl('HyperSpy','hyperspy._signals.signal2d','Signal2D','__init__ calibrate crop_signal','signal','图像构造、像素标定与裁剪。'),signal_base()],sources=src([A+'finding_atom_lattices.html',A+'analysing_atom_lattices.html',A+'quantification.html']),
      tasks=[task('07.02.02','detect_and_refine_atomic_columns','在64×64固定九高斯图中检测九列并以近邻→质心→二维高斯精化，最大位置误差<1e-4像素。','中心为{16.2,32.3,48.1}×{16.1,32.2,48.3}，sigma1.3；独立制造位置。',[('图像与初始列',['hyperspy._signals.signal2d.Signal2D.__init__','atomap.atom_finding_refining.get_atom_positions']),('构建并精化',['atomap.sublattice.Sublattice.__init__','atomap.sublattice.Sublattice.find_nearest_neighbors','atomap.sublattice.Sublattice.refine_atom_positions_using_center_of_mass','atomap.sublattice.Sublattice.refine_atom_positions_using_2d_gaussian','atomap.sublattice.Sublattice.atom_positions'])],['列数9','无序坐标匹配误差<1e-4']),
        task('07.02.02','repair_peak_separation','峰间隔24像素导致0个峰，恢复7像素并完整重精化；坐标JSON保存九列及像素单位。','原图和固定oracle不变，只允许修复separation。',[('重新检测和精化',['atomap.atom_finding_refining.get_atom_positions','atomap.sublattice.Sublattice.__init__','atomap.sublattice.Sublattice.find_nearest_neighbors','atomap.sublattice.Sublattice.refine_atom_positions_using_center_of_mass','atomap.sublattice.Sublattice.refine_atom_positions_using_2d_gaussian','atomap.sublattice.Sublattice.atom_positions'])],['修复后九列','相同原始容差'])],entity_attributes=['image','xy_pixels','pixel_scale','separation','sublattice','neighbors','fit_history','coordinate_unit'],bridge_contract='HyperSpy.Signal2D→Atomap.get_atom_positions的Nx2 xy坐标→Sublattice；数组yx索引与xy坐标不同，尺度从像素显式转物理单位。'))
    designs.append(dict(scenario_id='07.02.03',description='以abTEM构造电子波、投影势和多片传播得到TEM/STEM信号，能量eV、长度Angstrom、采样、分片厚度和强度归一化组成状态；先用常量投影势独立相位解验证传播和keV/eV修复，不把这一制造验收当成真实原子势准确性。',packages=[('abTEM','primary','电子波与多片传播唯一实现；与pyxem所需zarr版本冲突，运行隔离且不混同环境。')],symbols=[
      cl('abTEM','abtem.waves','PlaneWave','__init__ tilt normalize build multislice','wave','平面波参数到显式波阵列/传播。'),
      cl('abTEM','abtem.waves','Waves','__init__ normalize ensure_reciprocal_space ensure_real_space phase_shift to_images intensity phase real imag downsample diffraction_patterns apply_ctf multislice scan','propagate','波函数、CTF与衍射输出的主动作，排除重复show。'),
      cl('abTEM','abtem.potentials.iam','PotentialArray','__init__ from_array_and_metadata transmission_function transmit','potential','明确投影势数组、分片厚度和透射函数。'),
      cl('abTEM','abtem.array','ArrayObject','shape axes_metadata array dtype is_lazy compute to_cpu to_zarr from_zarr to_hyperspy mean sum','array','波/测量共同继承的数组、延迟计算及持久化；不直接构造无物理轴的抽象基对象。','由Waves、PotentialArray和测量对象继承。'),
      cl('abTEM','abtem.measurements','Images','sampling extent coordinates integrate_disc crop','measurement','像平面信号坐标、区域积分和裁剪。','Waves.intensity/to_images产生。'),
      cl('abTEM','abtem.measurements','DiffractionPatterns','sampling angular_sampling max_angles extent coordinates integrate_radial center_of_mass polar_binning','measurement','衍射坐标和探测器积分，不重复提供第二图像容器。','Waves.diffraction_patterns产生。')]+fn('abTEM','abtem.core.energy','energy2wavelength energy2sigma','units','电子能量到相对论波长/相互作用系数，eV与Angstrom合同显式化。'),sources=src([B+'wave_functions.html',B+'potentials.html',B+'multislice.html']),
      tasks=[task('07.02.03','simulate_constant_potential_tem','200keV平面波经过总20V*A常量投影势，32×32出射波等于独立SI公式exp(i sigma20)，强度1，总1024。','extent8A，两片各10V*A，slice_thickness1A，无真实原子IAM假设。',[('创建波和投影势',['abtem.waves.PlaneWave.__init__','abtem.waves.PlaneWave.build','abtem.potentials.iam.PotentialArray.__init__']),('传播及读强度',['abtem.waves.Waves.multislice','abtem.waves.Waves.intensity','abtem.array.ArrayObject.array'])],['相位.0145768021rad','复振幅原atol2e-7/rtol1e-7','像素强度atol2e-6']),
        task('07.02.03','repair_electron_energy_unit','错误200eV波长约.8671A必须拒绝；来源200keV显式乘1000恢复200000eV，波长约.02507934A。','独立SI常数和来源单位保留。',[('计算并修复波长',['abtem.core.energy.energy2wavelength'])],['错误波长大于正确30倍','修复相对误差<1e-7'])],entity_attributes=['energy_eV','extent_A','grid_points','slice_thickness_A','projected_potential','wave','normalization','measurement_axes'],bridge_contract='PlaneWave.build→Waves.multislice(PotentialArray)→Images/DiffractionPatterns；只通过带单位数组/HSpy交换到分析环境，不共用互斥zarr依赖。'))
    designs.append(dict(scenario_id='07.03.01',description='将EBSD原图、背景、探测器几何、扫描坐标和质量图作为状态；kikuchipy完成背景/强度/邻域处理，HyperSpy提供底层信号与IO。保存原图，用固定制造背景独立恢复与错误形状拒绝构成可验证任务。',packages=[('kikuchipy','primary','EBSD图样处理和探测器合同。'),('HyperSpy','complement','原始数据/元数据和通用信号读写，不重复领域预处理。')],symbols=[
      cl('kikuchipy','kikuchipy.signals.ebsd','EBSD','__init__ detector static_background extract_grid set_scan_calibration set_detector_calibration remove_static_background remove_dynamic_background get_dynamic_background fft_filter average_neighbour_patterns downsample get_image_quality get_average_neighbour_dot_product_map get_virtual_bse_intensity save crop rebin rescale_intensity normalize_intensity adaptive_histogram_equalization as_lazy change_dtype deepcopy','preprocess','图样预处理与质量诊断，物相/取向索引在独立场景处理。'),
      cl('kikuchipy','kikuchipy.detectors._ebsd_detector','EBSDDetector','__init__ pc pc_average shape px_size binning sample_tilt tilt to_gnomonic_coords to_pixel_coords crop deepcopy load save','detector','物理探测器、像素和投影中心，避免混淆scan shape与detector shape。'),signal_base('data metadata original_metadata sum mean get_current_signal transpose')]+fn('HyperSpy','hyperspy.io','load','io','通用信号读入保留插件与版本；本批只制造像素样例。'),sources=src([K+'pattern_processing.html',K+'feature_maps.html',K+'pattern_matching.html']),
      tasks=[task('07.03.01','correct_ebsd_pattern_background','固定1×2×8×8图减去30+2x背景后按库合同缩放至uint8的0..255，独立减法/重缩放atol1，原图不变。','已知特征4*(x+2y)与翻转副本，inplace=False。',[('构造与背景校正',['kikuchipy.signals.ebsd.EBSD.__init__','kikuchipy.signals.ebsd.EBSD.remove_static_background','hyperspy.signal.BaseSignal.data'])],['量化误差≤1','原始数组不变']),
        task('07.03.01','repair_background_detector_shape','7×8错误背景必须ValueError，按真实探测器恢复8×8并得到同一正确结果。','原图8×8和已知背景来源，禁止裁剪原图迎合错误。',[('恢复背景重算',['kikuchipy.signals.ebsd.EBSD.remove_static_background','hyperspy.signal.BaseSignal.data'])],['错误包含shapes are not the same','修复像素精确一致'])],entity_attributes=['raw_patterns','static_background','dtype','rescaling_policy','detector_shape','projection_center','scan_coordinates','quality_map'],bridge_contract='HyperSpy数据/元数据→kikuchipy.EBSD与EBSDDetector；背景只匹配signal shape，校正结果重缩放不保留绝对计数。'))
    designs.append(dict(scenario_id='07.03.02',description='kikuchipy以字典匹配为唯一EBSD索引主路径，orix维护旋转、相和空间地图；把字典图样与取向标签绑定，输出索引/分数/取向追溯到扫描点。固定制造图样验证NCC置换与错误标签修复，真实物相及取向精度仍需物理master-pattern。',packages=[('kikuchipy','primary','选dictionary_indexing及相关精化，不加入功能重叠的Hough索引后端。'),('orix','complement','旋转/晶体地图与物相身份，避免手写欧拉角到四元数。')],symbols=[
      cl('kikuchipy','kikuchipy.signals.ebsd','EBSD','__init__ detector xmap set_scan_calibration set_detector_calibration dictionary_indexing refine_orientation refine_projection_center refine_orientation_projection_center deepcopy save normalize_intensity','index','字典匹配、地图绑定和可选精化；当前固定任务不声明真实角度精度。'),
      cl('orix','orix.crystal_map.crystal_map','CrystalMap','__init__ id size shape x y phase_id phases rotations orientations is_indexed prop deepcopy get_map_data','map','地图位置/取向/物相/匹配属性保持身份。'),
      cl('orix','orix.quaternion.quaternion','Quaternion','from_euler from_matrix from_axes_angles to_euler to_matrix to_axes_angles identity angle','rotation','Rotation继承的确定性取向构造与表示转换，欧拉角单位按API合同。','Rotation类继承工厂返回旋转对象。'),
      cl('orix','orix.quaternion.rotation','Rotation','__init__ unique angle_with inv','rotation','离散取向去重、夹角与逆映射。'),
      cl('orix','orix.crystal_map._phase','Phase','__init__ name structure space_group point_group from_cif','phase','字典晶体相与结构引用。'),
      cl('orix','orix.crystal_map._phase_list','PhaseList','__init__ names ids size id_from_name add add_not_indexed','phase','物相列表及未索引状态，不能将未知自动分到已知相。')],sources=src([K+'pattern_matching.html',K+'pattern_processing.html','https://orix.readthedocs.io/en/stable/tutorials/crystal_map.html']),
      tasks=[task('07.03.02','match_ebsd_dictionary','三个固定字典图x/y/4*((x+y)%3)，观测顺序[2,0,1]并乘2加10；NCC应选2/0/1、分数1且输出四元数对应同一字典行。','字典旋转0/30/60deg，由Rotation.from_euler构造并绑定CrystalMap。',[('旋转与字典状态',['orix.quaternion.quaternion.Quaternion.from_euler','orix.crystal_map.crystal_map.CrystalMap.__init__','kikuchipy.signals.ebsd.EBSD.__init__','kikuchipy.signals.ebsd.EBSD.xmap']),('匹配读取',['kikuchipy.signals.ebsd.EBSD.dictionary_indexing','orix.crystal_map.crystal_map.CrystalMap.prop','orix.crystal_map.crystal_map.CrystalMap.rotations'])],['索引[2,0,1]','分数1','四元数atol1e-12']),
        task('07.03.02','repair_dictionary_orientation_binding','只把字典标签错移为[1,2,0]会保留像素匹配却给错取向；恢复原字典xmap后同一观测重匹配取向正确。','原始字典和错误副本独立，不能改oracle为错误标签。',[('复制并重绑',['kikuchipy.signals.ebsd.EBSD.deepcopy','orix.crystal_map.crystal_map.CrystalMap.__init__','kikuchipy.signals.ebsd.EBSD.xmap']),('重匹配',['kikuchipy.signals.ebsd.EBSD.dictionary_indexing','orix.crystal_map.crystal_map.CrystalMap.rotations'])],['错误四元数拒绝','恢复同一索引与正确标签'])],entity_attributes=['experimental_patterns','dictionary_patterns','dictionary_rotation_rows','phase_list','projection_center','map_coordinates','matching_scores','indexed_mask'],bridge_contract='orix.Rotation/CrystalMap绑定kikuchipy.EBSD字典，dictionary_indexing返回CrystalMap；任何图样行重排必须同步标签，NCC高分不足以证明标签正确。'))
    designs.append(dict(scenario_id='07.03.03',description='pyxem提供电子衍射预处理、直射束中心化、倒易标定和一/二维方位积分，HyperSpy负责底层数据与副本/保存；束位移xy与数组yx、倒易单位和标定来源为显式状态，固定偏心高斯验证定位与符号错误修复。',packages=[('pyxem','primary','主选电子衍射专用处理/标定，排除重复pyFAI积分和第二套峰分析。'),('HyperSpy','complement','底层信号数据、副本、元数据及读写。')],symbols=[
      cl('pyxem','pyxem.signals.diffraction2d','Diffraction2D','__init__ apply_affine_transformation shift_diffraction rotate_diffraction flip_diffraction_x flip_diffraction_y get_direct_beam_mask apply_gain_normalisation subtract_diffraction_background find_dead_pixels find_hot_pixels correct_bad_pixels get_direct_beam_position center_direct_beam threshold_and_mask template_match_disk template_match_ring get_diffraction_vectors peak_position_refinement_com intensity_peaks angular_mask get_variance get_azimuthal_integral1d get_azimuthal_integral2d','diffraction','电子图样预处理、中心化、峰/径向结果；不加入重复绘图或与4D重构混杂。'),
      cl('pyxem','pyxem.utils.calibration','Calibration','__init__ convert_signal_units set_mrad_scale_from_calibration set_camera_length_from_calibration affine mask scale units camera_length physical_pixel_size convergence_angle wavelength beam_energy detector_gain detector shape pixel_extent center','calibration','倒易单位、束能和探测器标定，状态变化要求派生结果重算。'),
      cl('pyxem','pyxem.signals.beam_shift','BeamShift','pixels_to_calibrated_units get_magnitude_signal rotate_beam_shifts rotate_scan_dimensions','beam','中心位移作为信号保留坐标约定，不将方向误差隐藏到绘图。','get_direct_beam_position返回，继承Signal2D/HyperSpy构造。'),signal_base('data metadata original_metadata deepcopy save crop rebin')],sources=src([P+'centering_the_zero_beam.html',P+'azimuthal_integration.html',P+'calibrating_recip_space.html']),
      tasks=[task('07.03.03','center_electron_diffraction_beam','32×32制造高斯XY=(12,19)，求出的xy修正为(+4,-3)，中心化后的最大值YX=(16,16)。','导航1×1，原图与独立高斯中心固定。',[('构造和求中心',['pyxem.signals.diffraction2d.Diffraction2D.__init__','pyxem.signals.diffraction2d.Diffraction2D.get_direct_beam_position']),('中心化读取',['pyxem.signals.diffraction2d.Diffraction2D.center_direct_beam','hyperspy.signal.BaseSignal.data'])],['位移atol1e-10','中心16,16']),
        task('07.03.03','repair_beam_shift_sign','错误位移符号会把峰移到YX=(22,8)，恢复正确位移并设置.05 k_A^-1像素尺度，保持正确中心。','错误副本不修改原位移信号；单位按pyxem校准合同。',[('副本和重中心化',['hyperspy.signal.BaseSignal.deepcopy','hyperspy.signal.BaseSignal.data','pyxem.signals.diffraction2d.Diffraction2D.center_direct_beam']),('绑定倒易尺度',['pyxem.utils.calibration.Calibration.scale','pyxem.utils.calibration.Calibration.units'])],['错误峰位置拒绝','修复同一像素','倒易尺度.05'])],entity_attributes=['raw_diffraction','beam_shift_xy','detector_yx','reciprocal_scale','calibration_unit','camera_length','beam_energy','processed_signal'],bridge_contract='Diffraction2D→BeamShift→center_direct_beam→Calibration；BaseSignal.deepcopy保留原始记录，位移xy与ndarrayyx必须转换。'))
    designs.append(dict(scenario_id='07.03.04',description='以py4DSTEM统一Rx/Ry/Qx/Qy四维数据、实/倒易尺度和虚拟探测器，先闭合导入、预处理、虚拟图、平均衍射与错误掩码修复。固定正式v0.14.8源码和Python3.11，不混用后续0.14.9相位检索接口；高级应变/重构不计为已验证能力。',packages=[('py4DSTEM','primary','DataCube/Calibration和虚拟探测主实现，避免再加入重复LiberTEM/pyxem归约；跨环境桥接需显式轴顺序。')],symbols=[
      cl('py4DSTEM','py4DSTEM.datacube.datacube','DataCube','__init__ calibrate R_Nx R_Ny Q_Nx Q_Ny Rshape Qshape R_N Q_pixel_size Q_pixel_units R_pixel_size R_pixel_units copy set_scan_shape swap_RQ swap_Rxy swap_Qxy crop_Q crop_R bin_Q pad_Q resample_Q bin_R thin_R filter_hot_pixels get_vacuum_probe get_probe_size','cube','轴形状、标定及必要预处理，排除legacy13重复API和本次未闭合相位重构。'),
      cl('py4DSTEM','py4DSTEM.datacube.virtualimage','DataCubeVirtualImager','get_virtual_image position_detector get_calibrated_detector_geometry make_detector make_bragg_mask','virtual','DataCube继承的虚拟探测操作，在定义处计数，不重建mixin对象。','由DataCube继承。'),
      cl('py4DSTEM','py4DSTEM.datacube.virtualdiffraction','DataCubeVirtualDiffraction','get_virtual_diffraction get_dp_max get_dp_mean get_dp_median','virtual','对扫描轴归约返回衍射信号。','由DataCube继承。'),
      cl('py4DSTEM','py4DSTEM.data.calibration','Calibration','__init__ set_Q_pixel_size get_Q_pixel_size set_R_pixel_size get_R_pixel_size set_Q_pixel_units get_Q_pixel_units set_R_pixel_units get_R_pixel_units set_origin get_origin get_origin_mean get_origin_shift set_ellipse get_ellipse set_QR_rotation get_QR_rotation set_QR_flip get_QR_flip copy to_h5 from_h5','calibration','实倒易尺度、原点/椭圆/旋转和持久化，去除同义属性与legacy别名。')]+fn('py4DSTEM','py4DSTEM.io.read','read','io','读取固定版本原生EMD数据。')+fn('py4DSTEM','py4DSTEM.io.save','save','io','保存原生数据与元数据，当前固定运行只内存数据。')+fn('py4DSTEM','py4DSTEM.io.importfile','import_file','io','非原生文件显式导入；格式兼容需单独固定样例。'),sources=src([Y+'api/classes.html',Y+'examples.html','https://github.com/py4dstem/py4DSTEM']),
      tasks=[task('07.03.04','build_4dstem_virtual_detector','2×3×8×8 arange制造数据在Qx2:5/Qy3:6积分，虚拟图[[252,828,1404],[1980,2556,3132]]；平均衍射等于独立导航均值。','DataCube轴按Rx/Ry/Qx/Qy，R2nm、Q.05A^-1明确。',[('创建及虚拟探测',['py4DSTEM.datacube.datacube.DataCube.__init__','py4DSTEM.datacube.virtualimage.DataCubeVirtualImager.get_virtual_image','py4DSTEM.datacube.virtualdiffraction.DataCubeVirtualDiffraction.get_dp_mean']),('设置尺度',['py4DSTEM.data.calibration.Calibration.set_Q_pixel_size','py4DSTEM.data.calibration.Calibration.set_Q_pixel_units','py4DSTEM.data.calibration.Calibration.set_R_pixel_size','py4DSTEM.data.calibration.Calibration.set_R_pixel_units'])],['固定六位置计数','平均衍射逐元素相等']),
        task('07.03.04','repair_virtual_detector_axis_order','掩码转置导致[[315,891,1467],[2043,2619,3195]]，恢复正确Qx/Qy方向后重积分满足原计数，并查询保留尺度。','原始DataCube和规定探测区域不变。',[('修复探测器并积分',['py4DSTEM.datacube.virtualimage.DataCubeVirtualImager.get_virtual_image']),('检查尺度',['py4DSTEM.data.calibration.Calibration.get_Q_pixel_size','py4DSTEM.data.calibration.Calibration.get_R_pixel_size'])],['转置错误计数拒绝','修复原六值','实倒易单位和尺度不变'])],entity_attributes=['datacube_RxRyQxQy','real_pixel_nm','reciprocal_pixel_A_inverse','detector_mask_QxQy','origin','virtual_image','mean_diffraction','calibration_revision'],bridge_contract='DataCube继承virtualimage/virtualdiffraction方法，返回数据及原标定；与常见numpy(y,x)图桥接必须记录轴置换而非默认为相同。'))
    for d in designs:
        d['capabilities']=list(dict.fromkeys(s['capability'] for s in d['symbols']))
        d['entities']=[{'name':'source_measurement','identity':'scan_id/source_hash','attributes':d.pop('entity_attributes'),'lifecycle':'获取/构造→冻结原始像素和单位→配置→版本化派生；修复不得改写原始oracle。'},
          {'name':'analysis_configuration','identity':'configuration_id/revision','attributes':['package_version','axis_order','units','mask','model_parameters','source_refs'],'lifecycle':'显式配置→检查形状/单位/引用→执行；参数变化使旧结果失效。'},
          {'name':'derived_result','identity':'result_id','attributes':['source_id','configuration_id','data','diagnostics','verification','output_path'],'lifecycle':'计算→独立固定oracle验收→保留失败证据→修复后重算；不允许只改结果冒充修复。'}]
        d['bridges']=[{'from':'source_measurement','to':'selected_package_objects and derived_result','contract':d.pop('bridge_contract')}]
        d['runtime_infrastructure']=[{'reference':'python.numpy_math_json_pathlib','kind':'infrastructure','reason':'制造独立已知图/数组、轴求和和物理解析oracle；保存小型JSON/RAW，不包含另一个未选领域算法。'},
          {'reference':'runtime.scientific_attributes_and_indexing','kind':'infrastructure','reason':'实例普通属性如orix Rotation.data、py4输出data/calibration及numpy索引；这些不是可单独提取的顶层方法，不伪造来源API。'}]
        d['count_exception']='只选使本场景输入/配置/处理/输出/诊断修复闭合的高层接口；继承方法按定义处计一次，若低于50不以内部worker/tile调度、绘图和重复替代后端凑数。'
        d['boundaries']=['仅每场景两条制造固定任务实际运行，不代表全部选择的参考API、所有文件格式或真实仪器分析已经验证。','LiberTEM的Inline小数据不验证TB吞吐；Atomap只验九无噪声坐标且协方差警告不算置信度；EBSD字典图非物理模拟，未验证真实物相/取向精度。','abTEM只验常量势的独立相位/强度；pyxem只验中心化和尺度；py4DSTEM只验虚拟探测归约，未声称真实应变/相位检索性能。','abTEM与pyxem的zarr主版本互斥，使用隔离venv；py4DSTEM0.14.8固定源码需Python<3.12，实际使用3.11，在线较新文档仅参考。','尚未实现Agent持久状态、reset/step、并发隔离和硬件权限；当前产物为参考种子与可复现固定任务。']
        d['runtime_report']=(BASE/f'runtime/diffraction/{d["scenario_id"]}.json').as_posix()
        d['runtime_scope']='正常分析和错误配置修复各一条固定任务；独立制造坐标/像素/物理公式oracle，运行仅为明确子集。'
        c.write(d)

if __name__=='__main__':main()
