"""Joint wafer evidence/table/spatial selections with different taskchains."""
from pathlib import Path
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_metrology_quality_graph_profiles import tables,graphs,graph_functions,stats
BASE=Path('seed_gen/scenario_collection/l1_metrology_quality');RAW=Path('seed_gen/pypi_outputs/ori_all_funcs/scenario_collection/l1_metrology_quality')
def cl(p,m,n,methods,cap,why,construction=None):return symbol(p,m,n,methods,cap,why,construction)
def fn(p,m,names,cap,why):return [symbol(p,m,n,None,cap,why) for n in names.split()]
def estimator():return [cl('scikit-learn','sklearn.base','BaseEstimator','get_params set_params','config','继承模型配置的可审阅获取与修复，重新fit才能更新结果。','由DBSCAN/KNN等实例继承。')]
def distances():return fn('scipy','scipy.spatial.distance','pdist cdist squareform','distance','在明确XY单位或公共die特征空间计算独立距离并检查邻域。')
def main():
    c=Collection(base=BASE,raw=RAW);S='https://scikit-learn.org/stable/';P='https://pandas.pydata.org/docs/user_guide/';N='https://networkx.org/documentation/stable/'
    text={'https://github.com/cap1tan/wafermap':'半导体晶圆图实际代码描述notch、圆形wafer、die网格/标签/颜色和HTML导出；所有坐标输入XY，PNG额外需要Chromium。',
      'https://github.com/Semi-ATE/STDF':'ATE STDF库支持按记录类读写字段和转换ATDF，作为晶圆bin输入；格式解析本身不定义重测如何归并。',
      S+'auto_examples/cluster/plot_dbscan.html':'制造三簇示例介绍eps邻域、核心点和噪声，强调相近密度适用性及不能直接比较任意数值簇标签。',
      S+'modules/generated/sklearn.cluster.DBSCAN.html':'DBSCAN的eps具有输入距离单位，min_samples含自身，-1代表噪声；邻域查询与特征尺度共同决定聚类。',
      S+'auto_examples/classification/plot_classifier_comparison.html':'实际分类器比较展示独立训练/测试与决策边界，明确合成低维表现不能推广为真实数据准确率。',
      S+'modules/generated/sklearn.neighbors.KNeighborsClassifier.html':'近邻投票分类器区分fit、predict和概率；固定1近邻作为小型可解释图样标签环境。',
      S+'modules/generated/sklearn.metrics.pairwise.cosine_similarity.html':'余弦相似度明确等于向量点积除范数，支持公共die坐标下重复图样与独立解析oracle。',
      'https://archive.ics.uci.edu/dataset/179/secom':'实际半导体生产监测数据有1567生产实体、591特征、104失败，信号含缺失/噪声并要求交叉验证；用作来源/实体/标签关联依据，不冒充晶圆图数据。',
      P+'groupby.html':'按wafer/lot/设备键分组聚合并保留组大小，避免跨实体混合计数。',
      P+'merging.html':'不同连接方法和键对齐决定测量/制造谱系能否正确关联，不能以行号代替身份。',
      N+'reference/algorithms/generated/networkx.algorithms.dag.ancestors.html':'上游可达节点定义支持限定具有实际制造路径的设备候选。',
      'https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html':'固定边际的精确2x2关联检验，不等同设备因果概率。'}
    def src(urls):return [c.source(u,text[u],['wafer','die_xy','pattern_artifact','equipment'],['decode','group','classify','compare','trace'],['从制造固定图样到来源一致的分析和诊断修复']) for u in urls]
    def task(sid,tid,desc,initial,steps,checks):return recipe(tid,desc,initial,steps,checks,'verify_wafer.py:'+sid)
    common=[('pandas','complement','维护wafer/lot/die键、测量掩膜、标签与JSON结果，算法输入必须可反查原始行。')]
    designs=[dict(scenario_id='07.07.01',description='将ATE STDF中的晶粒身份、坐标与硬/软bin转换为逐die地图：保留重测尝试，按明确最终测试策略归并，再按XY间距、notch和边缘条件绘图。地图外观不替代bin/缺测/重测语义验证。',packages=[('Semi-ATE-STDF','primary','负责STDF字段解析；采用0.1.33官方tag而非旧PyPI版本。'),('wafermap','complement','按die坐标呈现颜色/标签并保存HTML，不解析测试记录。')]+common,
      symbols=tables()+[cl('Semi-ATE-STDF','Semi_ATE.STDF.utils','records_from_file','__init__ parse_FAR','decode','流式记录读取、文件头端序解析；迭代器语法作为语言基础设施。'),cl('Semi-ATE-STDF','Semi_ATE.STDF.STDR','STDR','get_fields get_value to_dict to_json to_atdf','decode','各记录继承字段读取/导出，不暴露修改生产测试文件的默认动作。','由records_from_file返回PRR/WIR/FAR等记录继承。'),cl('wafermap','wafermap.wafermap','WaferMap','__init__ save_html style_cell add_label add_point add_heatmap','render','主晶圆图表，HTML本地可导出，不选择浏览器截图。'),cl('wafermap','wafermap.wafermap','WaferMapGrid','cell_map cell_to_wafer_coordinates','coordinates','网格实例继承的die→wafer物理坐标查询。','WaferMap继承，不单独构造第二套网格。')],sources=src(['https://github.com/Semi-ATE/STDF','https://github.com/cap1tan/wafermap',P+'groupby.html',P+'merging.html']),
      tasks=[task('07.07.01','decode_and_render_binmap','读取制造STDF四条PRR，按最后attempt得到三die最终bin并绘HTML；核验两pass一fail和X/Y物理间距10mm。','D2首次失败、二次通过，原记录保留。',[('解析并规范记录',['Semi_ATE.STDF.utils.records_from_file.__init__','Semi_ATE.STDF.STDR.STDR.to_dict','pandas.core.frame.DataFrame.__init__']),('按attempt归并并绘图',['pandas.core.frame.DataFrame.sort_values','pandas.core.frame.DataFrame.drop_duplicates','wafermap.wafermap.WaferMap.__init__','wafermap.wafermap.WaferMap.style_cell','wafermap.wafermap.WaferMap.add_label','wafermap.wafermap.WaferMap.save_html','wafermap.wafermap.WaferMapGrid.cell_to_wafer_coordinates'])],['最终die3/pass2/fail1','相邻XY差10mm','HTML包含bin标签']),
        task('07.07.01','repair_retest_bin_selection','拒绝keep=first得到pass1，将归并改为按attempt排序保留last，恢复D2通过和pass2。','错误第一测结果被误称最终结果。',[('修复归并',['pandas.core.frame.DataFrame.sort_values','pandas.core.frame.DataFrame.drop_duplicates'])],['first与final语义不同','最终D2硬bin1'])]),
      dict(scenario_id='07.07.02',description='以带物理单位的失败die坐标为动作对象，使用DBSCAN定位密集失效区并明确保留噪声点；邻域半径、最小样本和坐标尺度必须同一契约，不能以任意簇编号充当物理身份。',packages=[('scikit-learn','primary','DBSCAN作为空间聚类主实现。'),('scipy','complement','距离表用于空间邻域诊断，不引入第二聚类求解器。')]+common,
      symbols=tables()+estimator()+[cl('scikit-learn','sklearn.cluster._dbscan','DBSCAN','__init__ fit fit_predict','cluster','密度聚类、噪声标注与重新拟合。')]+distances()+fn('scikit-learn','sklearn.metrics.cluster._unsupervised','silhouette_samples silhouette_score','diagnose','在存在至少两簇且合理掩除噪声时评价分离度，不能替代制造已知区域oracle。'),sources=src(['https://github.com/cap1tan/wafermap',S+'auto_examples/cluster/plot_dbscan.html',S+'modules/generated/sklearn.cluster.DBSCAN.html']),
      tasks=[task('07.07.02','cluster_failed_dies','对11个失败die以eps=.5mm、min_samples3聚类，验收0..4和5..9两组及10号噪声，输出几何中心。','两制造五点簇中心[-3,1]/[4,-2]及远离噪声。',[('拟合并取簇',['sklearn.cluster._dbscan.DBSCAN.__init__','sklearn.cluster._dbscan.DBSCAN.fit_predict'])],['分区按成员集合一致','噪声恰为10','距离上下界独立核验']),
        task('07.07.02','repair_spatial_units','诊断mm数据误用um数值但eps仍为.5造成全噪声，恢复坐标单位并重新拟合，回到两簇和一噪声。','错误坐标整体乘1000。',[('恢复单位并重算',['sklearn.cluster._dbscan.DBSCAN.__init__','sklearn.cluster._dbscan.DBSCAN.fit_predict'])],['错误噪声11','修复噪声1且固定成员恢复'])]),
      dict(scenario_id='07.07.03',description='将圆形wafer上的失败掩膜转换为按固定半径分箱的失败比例特征，以可解释1近邻识别中心、环状和划痕图样；训练/保留数据由不同缺die模式构造，冻结分箱次序和标签，结果限定为固定样例识别能力。',packages=[('scikit-learn','primary','KNN作为单一图样分类器，记录训练集版本和预测标签。'),('scipy','complement','binned_statistic生成明确定义的径向失败比例特征。')]+common,
      symbols=tables()+estimator()+[cl('scikit-learn','sklearn.neighbors._classification','KNeighborsClassifier','__init__ fit predict predict_proba score','classify','简单局部投票主实现，固定训练与保留图样。')]+fn('scipy','scipy.stats._binned_statistic','binned_statistic','features','按归一化wafer半径计算失败率，边界/分箱次序就是模型输入模式。')+fn('scikit-learn','sklearn.metrics._classification','confusion_matrix classification_report balanced_accuracy_score','evaluate','按显式标签顺序报告保留样例，不能把训练分数当泛化。'),sources=src(['https://github.com/cap1tan/wafermap',S+'auto_examples/classification/plot_classifier_comparison.html',S+'modules/generated/sklearn.neighbors.KNeighborsClassifier.html']),
      tasks=[task('07.07.03','recognize_wafer_shapes','为制造center/ring/scratch训练图与独立缺die保留图计算5段径向失败比例，用1近邻预测并得到三类单位混淆矩阵。','六训练图、三保留图，掩膜生成参数和缺测规则不同。',[('提取并固定特征',['scipy.stats._binned_statistic.binned_statistic']),('训练与保留评估',['sklearn.neighbors._classification.KNeighborsClassifier.__init__','sklearn.neighbors._classification.KNeighborsClassifier.fit','sklearn.neighbors._classification.KNeighborsClassifier.predict','sklearn.metrics._classification.confusion_matrix'])],['保留预测等于几何定义标签','混淆矩阵diag1','不使用训练输入评估']),
        task('07.07.03','repair_radial_feature_order','识别半径分箱倒序导致分类错误，按原特征schema恢复内→外顺序，再用同一固定模型核验三个标签。','错误是输入schema顺序，不改变训练标签或目标。',[('修复输入并预测',['sklearn.neighbors._classification.KNeighborsClassifier.predict'])],['倒序至少一项误判','修复三个正确'])]),
      dict(scenario_id='07.07.04',description='对同批/跨批晶圆图样按共同实测die和统一物理朝向进行相似度比较，以稳定wafer ID保存复现关系；未测die不能默认为pass，镜像/旋转要依notch和坐标来源校正。',packages=[('scikit-learn','primary','余弦相似度为二值图样复现主度量。'),('scipy','complement','距离/Jaccard诊断作为相似性假设核查，不复制分类器。')]+common,
      symbols=tables()+fn('scikit-learn','sklearn.metrics.pairwise','cosine_similarity cosine_distances pairwise_distances','similarity','公共实测die向量的规范化相似度及相应距离。')+distances()+fn('scipy','scipy.spatial.distance','jaccard hamming','similarity','可解释交并/不一致比例用于不同稀疏图样的对照，保留明确分母。')+[cl('scikit-learn','sklearn.neighbors._unsupervised','NearestNeighbors','__init__ fit','retrieve','当批次图样较多时索引相似wafer。'),cl('scikit-learn','sklearn.neighbors._base','KNeighborsMixin','kneighbors kneighbors_graph','retrieve','由近邻索引返回候选和关系，不额外构造分类模型。','NearestNeighbors继承。')],sources=src(['https://github.com/cap1tan/wafermap',S+'modules/generated/sklearn.metrics.pairwise.cosine_similarity.html',P+'groupby.html']),
      tasks=[task('07.07.04','compare_lot_pattern_recurrence','在24个共同实测die上比较三张图；A/B共享3个且B有4个失败，相似度sqrt3/2，A/C不相交为0，并保留lot/wafer来源。','两张同批一张跨批5×5制造图，角点未测排除。',[('公共坐标特征比较',['sklearn.metrics.pairwise.cosine_similarity'])],['独立点积值sqrt3/2','不相交0','未测die不计入']),
        task('07.07.04','repair_wafer_orientation_alignment','诊断B水平镜像使相似度误降0，按已知notch/坐标来源恢复物理方向后重新比较，回到sqrt3/2。','错误图列翻转，原物理方向元数据冻结。',[('修复朝向重新比较',['sklearn.metrics.pairwise.cosine_similarity'])],['错误0被拒绝','修复解析目标'])]),
      dict(scenario_id='07.07.05',description='把具有版本的wafer图样结果连接到设备腔室与工艺路径，按wafer主键统计图样出现率并检查上游关系；只输出受证据支持的设备关联候选，保留正常wafer和交叉路径反证。',packages=[('networkx','primary','管理chamber→process→wafer→pattern artifact谱系。'),('scipy','complement','Fisher精确关联量化，在固定边际下比较出现率。')]+common,
      symbols=tables()+graphs()+graph_functions()+stats('fisher_exact')+fn('pandas','pandas.core.reshape.pivot','crosstab','aggregate','按腔室和图样标志建立具名列联表。'),sources=src(['https://archive.ics.uci.edu/dataset/179/secom',N+'reference/algorithms/generated/networkx.algorithms.dag.ancestors.html','https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html',P+'merging.html']),
      tasks=[task('07.07.05','associate_patterns_with_upstream_equipment','对20个制造wafer的ring结果与腔室谱系关联，A8/10、B2/10；报告ring OR16与组合数独立验算的p=.023014，并限制实际上游候选。','预存pattern_artifact和chamber/process/wafer身份，非因果干预。',[('建路径并查询上游',['networkx.classes.digraph.DiGraph.__init__','networkx.classes.digraph.DiGraph.add_edge','networkx.algorithms.dag.ancestors']),('列联与精确检验',['pandas.core.frame.DataFrame.__init__','pandas.core.reshape.pivot.crosstab','scipy.stats._stats_py.fisher_exact'])],['8/2ring','精确p一致','A-0路径不含B']),
        task('07.07.05','repair_pattern_genealogy','检测错误B→process:A-0边污染候选，将其按固定制造日志移除；JSON往返后保留正确上游链和DAG。','错误交叉腔室边，原日志仍在。',[('修复边并验证',['networkx.classes.graph.Graph.copy','networkx.classes.digraph.DiGraph.remove_edge','networkx.algorithms.dag.ancestors','networkx.algorithms.dag.is_directed_acyclic_graph']),('保存恢复',['networkx.readwrite.json_graph.node_link.node_link_data','networkx.readwrite.json_graph.node_link.node_link_graph'])],['污染边导致B误入','修复候选和来源链'])])]
    for d in designs:
        d['sources'].append(c.source('https://github.com/aws-samples/amazon-ec2-nice-dcv-semiconductor-wafer-data',
            'AWS实际WM811K教程展示811457晶圆图及waferMap/dieSize/lotName/waferIndex/trainTestLabel/failureType字段，区分空白/good/defective并列出Center/Donut/Edge-Ring/Scratch等；只借鉴公开样例状态/任务，未启动云服务或下载全数据。',
            ['lotName','waferIndex','waferMap','trainTestLabel','failureType'],['filter_by_lot','map_die_state','compare_patterns'],['带身份和训练/测试边界的晶圆图样任务']))
        d['capabilities']=list(dict.fromkeys(s['capability'] for s in d['symbols']))
        d['entities']=[{'name':'wafer_die_ledger','identity':'lot_id/wafer_id/die_xy/attempt','attributes':['bin','measured','timestamp','source_hash','notch','pitch_unit'],'lifecycle':'解码→保留重测→按显式策略归并→坐标标准化；未测不同于pass。'},
          {'name':'pattern_configuration','identity':'analysis_id','attributes':['distance_unit','eps','min_samples','radial_bins','label_order','training_ids','measured_mask'],'lifecycle':'固定数据/轴/训练及验收→执行→诊断→修复；schema改变需重提特征/拟合。'},
          {'name':'pattern_result','identity':'pattern_artifact_id','attributes':['wafer_ref','cluster_members','noise','features','label','similarity','revision'],'lifecycle':'生成→固定几何/独立公式验收→导出；不以任意簇编号充当物理身份。'},
          {'name':'equipment_genealogy','identity':'source_record_id','attributes':['chamber','step','wafer','pattern_revision','counterexamples','association'],'lifecycle':'按主键/日志建路径→检验上游→关联比较→保存，统计显著不能自动确认根因。'}]
        d['bridges']=[{'from':'STDFdie fields / keyedpandas rows / failuremasks','to':'wafermapXY or sklearn/scipy features or NetworkXgenealogy accordingto selectedpackages','contract':'统一物理XY、notch、单位和wafer身份；算法数组保留行/die映射，谱系绑定pattern版本，缺测与pass分开。'}]
        d['runtime_infrastructure']=[{'reference':'python.numpy_json_struct_math','kind':'infrastructure','reason':'固定STDF字节fixture、已知几何掩膜、坐标单位/镜像转换、数组索引及独立距离/点积/组合数oracle；分类/聚类/分箱统计均使用已选包API。'},
          {'reference':'runtime.pandas_iteration_access','kind':'infrastructure','reason':'[]、itertuples和列属性等记录访问语法，STDF迭代器dunder和图节点属性访问；不新增隐藏领域算法。'}]
        d['boundaries']=['仅制造小样例正常/故障修复实跑；不是真实晶圆图分类准确率、产线良率或根因验证。','Semi-ATE-STDF源码tag0.1.33安装元数据0.0.0，保留实际commit作为版本依据；wafermap与wfmap不同，本场景采用前者。','HTML已生成并检查标签及XY几何；未运行浏览器视觉/PNG截图验收。','后续Agent封装仍需状态注册/重置、固定验收、来源权限与跨任务隔离；未接外部MES/QMS。']
        d['runtime_report']=(BASE/f'runtime/wafer/{d["scenario_id"]}.json').as_posix();d['runtime_scope']='每场景两条固定制造任务和错误修复；几何集合/独立公式/固定来源图oracle。';c.write(d)
if __name__=='__main__':main()
