"""Joint released-source EDA selections, grounded in four real local fixtures."""
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_design_lab_sources import BASE,RAW


def item(package,module,name,methods,cap,reason,construction=None):
    return symbol(package,module,name,methods,cap,reason,construction)


def base(sid,description,packages,sources,symbols,capabilities,entities,runtime,boundaries):
    return dict(scenario_id=sid,description=description,packages=packages,sources=sources,symbols=symbols,capabilities=capabilities,entities=entities,bridges=[],runtime_infrastructure=[],boundaries=boundaries,runtime_report=(BASE/f'runtime/{runtime}/{sid}.json').as_posix(),runtime_scope='真实固定版本正常/错误/修复任务；仅runtime报告明确列出的局部能力实跑，不宣称全部参考接口逐项通过。')


def main():
    c=Collection(base=BASE,raw=RAW)
    sc=lambda module,name,methods,cap,why,cons=None:item('siliconcompiler','siliconcompiler.'+module,name,methods,cap,why,cons)
    d=base('03.09.01','围绕SiliconCompiler的Design、Project及Flowgraph构建RTL到GDS流程状态空间：源文件和参数进入有依赖的步骤图，执行后保留结果、历史与指标，定位配置和结果错误。当前固定任务真实运行Slang前端并用Icarus独立验算，综合/布局布线/GDS后端保留为明确未验证扩展。',[('siliconcompiler','primary','统一源设计、流程、任务执行和结果状态。'),('librelane','excluded','与主流程编排功能重叠；保留全量候选和版本证据，不并列引入第二套Project/step状态。')],[
        c.source('https://github.com/siliconcompiler/siliconcompiler/blob/v0.38.8/examples/gcd/gcd.py','官方GCD例通过ASIC项目、fileset、target和ASICFlow配置完整流；目标后端/PDK是实际运行的前提。',['design','fileset','target','flow'],['Design','Project','ASICFlow'],['配置设计并逐步执行及检查结果']),
        c.source('https://github.com/siliconcompiler/siliconcompiler/blob/v0.38.8/tests/tools/test_slang.py','官方测试使用Design/Project与Elaborate单节点流，真实run并检查输出Verilog和metric；局部前端可独立验证。',['top_module','parameter','result','metric'],['Elaborate','Project.run','Project.find_result'],['错误top修复和位宽参数传播']),
        c.source('https://github.com/siliconcompiler/siliconcompiler/blob/v0.38.8/siliconcompiler/flows/asicflow.py','官方源码说明elaborate/synthesis/floorplan/place/CTS/route/DFM/write阶段及并行候选连接；不是只有输入配置文件。',['flow_node','edge','stage','strategy'],['ASICFlow','Flowgraph'],['在同一流程对象上追踪阶段依赖与失败'])],
        [sc('design','Design','__init__ add_file get_file has_file active_fileset copy_fileset has_fileset set_topmodule get_topmodule add_idir add_define add_libdir add_lib set_param get_param add_depfileset get_depfileset write_fileset read_fileset get_fileset','source','保留常用RTL/fileset/参数和依赖入口，删除冗余has/get目录别名。'),sc('schema_support.pathschema','PathSchema','set_dataroot get_dataroot active_dataroot','source','Design继承的源根上下文，不复制为虚构Design方法。','Design构造得到PathSchema协议。'),sc('schema_support.dependencyschema','DependencySchema','check_filepaths','source','执行前检验源路径。','Design/Project继承的路径检查协议。'),sc('flowgraph','Flowgraph','__init__ node edge remove_node insert_node rename_node graph get_nodes get_entry_nodes get_exit_nodes get_execution_order validate write_flowgraph get_graph_node','flow','创建/修复流程依赖并检查拓扑，删除文档和内部任务枚举。'),sc('project','Project','__init__ check_manifest run history get_filesets set_design set_flow get_flow add_fileset summary find_result snapshot','execute','单一执行入口和真实运行历史/工件定位；logger/name属性属于状态。'),sc('schema_support.option','OptionSchema','set_builddir set_jobname add_from add_to add_prune set_timeout set_nodisplay','execute','隔离构建目录、限定步骤/时间，删除远程凭据/宽泛clean动作。','Project.option提供真实选项对象。'),sc('schema.baseschema','BaseSchema','get getkeys getdict','observe','读取历史指标和结构，保留唯一基础定义。','Project.history返回Schema对象。'),sc('tools.slang.elaborate','Elaborate','__init__','flow','真实本地Slang展开任务，运行由Project调度。'),sc('flows.asicflow','ASICFlow','__init__','flow','官方完整ASIC流程入口；固定例仅验证前端，禁止宣称全流完成。')],['source','flow','execute','observe'],[
            dict(name='source_design',identity='design+fileset',attributes=['root','files','top_module','parameters'],lifecycle='register -> check -> elaborate -> revise and rerun'),dict(name='flow_run',identity='builddir+jobname+step+index',attributes=['dependency_graph','status','errors','outputs','history'],lifecycle='configure -> validate -> execute -> inspect -> repair；每次独立builddir。')],'siliconcompiler',['仅真实运行Slang本地前端和Icarus输出验证；未运行Yosys/OpenROAD/CTS/布线/GDS生成，没有真实PDK签核。','完整flow相关工具是已解析参考能力，后续必须提供外部工具与工艺并追加验证。'])
    d['runtime_infrastructure']=[dict(reference='pyslang11.0.0+Icarus12.0',kind='external_runtime',reason='Slang实际展开RTL，独立Icarus执行生成Verilog核对4点手写和；不是配置文本检查。')]
    d['tasks']=[recipe('repair_flow_topmodule','发现missing_top导致真实Slang节点失败，恢复adder并重跑；检查四组结果和无关模块剔除。','顶层adder、4点expected=[0,3,256,510]固定。',[('注册源及top',['siliconcompiler.design.Design.add_file','siliconcompiler.design.Design.set_topmodule']),('执行流程',['siliconcompiler.flowgraph.Flowgraph.node','siliconcompiler.project.Project.set_flow','siliconcompiler.project.Project.run']),('检查并修复',['siliconcompiler.project.Project.find_result','siliconcompiler.design.Design.set_topmodule','siliconcompiler.project.Project.run'])],['missing_top实际失败','修复errors=0','输出真实仿真四点匹配'],'verify_siliconcompiler.py:topmodule'),recipe('repair_flow_parameter_propagation','WIDTH=8虽成功展开却丢进位，恢复9后生成Verilog在独立仿真器中恢复正确结果。','不得改expected或跳过255+1与255+255。',[('设置参数',['siliconcompiler.design.Design.set_param']),('执行及定位输出',['siliconcompiler.project.Project.run','siliconcompiler.project.Project.find_result']),('修复参数复验',['siliconcompiler.design.Design.set_param','siliconcompiler.project.Project.run'])],['错误[0,3,0,254]','修复[0,3,256,510]','每次工件路径独立'],'verify_siliconcompiler.py:parameters')]
    c.write(d)

    fs=lambda module,name,methods,cap,why,cons=None:item('fusesoc','fusesoc.'+module,name,methods,cap,why,cons)
    ed=lambda module,name,methods,cap,why,cons=None:item('edalize','edalize.flows.'+module,name,methods,cap,why,cons)
    d=base('03.10.01','以FuseSoC管理固定CAPI2 IP、版本依赖、文件集和目标，解析为EDAM后交Edalize统一构建执行；由真实Icarus仿真与固定结果表验证依赖修复和参数传播，保持源码、构建目录和运行结果可追溯。',[('fusesoc','primary','管理IP语义、VLNV依赖与EDAM生成。'),('edalize','complement','接收同一EDAM调度实际后端；无第二套IP解析器。')],[
        c.source('https://fusesoc.readthedocs.io/en/stable/user/build_system/core_files.html','官方CAPI2教程定义filesets、targets、toplevel、参数类型与use作用域；core描述不能替代实际构建。',['core','fileset','target','parameter'],['CoreParser.read','CoreInterface.get_files','Edalizer.run'],['两核adder/tb装配并执行']),
        c.source('https://fusesoc.readthedocs.io/en/stable/user/build_system/dependencies.html','官方依赖教程说明VLNV版本约束与依赖解析，多个core复用时统一排序/求解。',['vlnv','dependency','resolved_core'],['Vlnv','CoreManager.get_depends','Edalizer.run'],['不存在adder2.0依赖修回1.0']),
        c.source('https://github.com/olofk/fusesoc/blob/2.4.7/tests/test_edalizer.py','固定版本测试从CoreManager和Edalizer构建EDAM；export会把源放到src树，运行前不能漏掉。',['edam','exported_source','work_root'],['Edalizer.run','Edalizer.export'],['源文件导出后构建']),
        c.source('https://github.com/olofk/edalize/blob/v0.6.7/edalize/flows/sim.py','固定版本Sim flow读取flow_options构建仿真图并执行；iverilog_options属于新flow schema，旧tool_options路径不能代替。',['simulation_flow','flow_options','backend'],['Sim.configure','Edaflow.build','Sim.run'],['位宽8错误经真实仿真暴露'])],
        [fs('config','Config','__init__ write add_library','core','显式配置与本地库，不保留宽泛路径属性getter作为动作。'),fs('library','Library','__init__','core','命名本地IP库。'),fs('librarymanager','LibraryManager','__init__ add_library get_library get_libraries','core','查询与登记本地库，删除外网update。'),fs('coremanager','CoreManager','__init__ find_cores add_library get_libraries get_depends get_cores get_core','core','核心发现、定位和依赖求解。'),fs('vlnv','Vlnv','__init__ depstr simpleVLNVs vln_str','core','版本化引用与依赖表示。'),fs('parser.coreparser','CoreParser','read write validate get_version get_preamble get_schema','core','源schema验证与读写。','Core2Parser继承的协议，不实例化缺少schema的基类。'),fs('capi2.coreparser','Core2Parser','__init__','core','创建CAPI2解析器。'),fs('capi2.core','CoreInterface','get_data get_target get_flags get_flow get_scripts get_flow_options get_depends get_files get_parameters get_toplevel get_description get_license','core','保留构建所需IP描述查询，删除签名打印/内部patch。','CoreManager.get_core返回Core，该类继承CoreInterface。'),fs('core','Core',[],'core','实际core模型，字段状态保留。','由CoreManager.get_core创建/返回，继承CoreInterface，源类无独立构造。'),fs('edalizer','Edalizer','__init__ run export create_edam add_parsed_args parse_args to_yaml','bridge','解依赖/生成EDAM/导出源的主链，内部setup/generator循环由run负责。'),ed('edaflow','Edaflow','__init__ get_flow_options get_tool_options configure build run','execute','新flow公共生命周期只保留一次；具体Sim覆盖configure/run。'),ed('sim','Sim','configure run','execute','实际仿真flow入口，不调用内部configure_tools。','继承Edaflow.__init__与build；正常Sim(edam,work_root)构造。'),ed('edaflow','FlowGraph','__init__ fromdict add_node get_node get_nodes','execute','后端有依赖图时保留有限建图/查询，避免加入每种工具CLI包装。')],['core','bridge','execute'],[dict(name='ip_library',identity='library+VLNV',attributes=['source_root','filesets','targets','dependencies','parameters'],lifecycle='register -> parse -> resolve -> fix missing version'),dict(name='build_job',identity='export_root+work_root',attributes=['EDAM','ordered_files','options','binary','observed_values'],lifecycle='edalize -> export -> configure -> build -> run -> compare')],'fusesoc',['实际运行两个本地IP core和Icarus仿真；未下载第三方IP、未综合或流片。','Edalize0.6.7采用新flow API；PyPI0.6.8未替换固定发布版本。'])
    d['bridges']=[dict(**{'from':'FuseSoC resolved CAPI2 cores','to':'Edalize Sim flow','tool':'Edalizer.run/export -> Sim.configure -> Edaflow.build -> Sim.run'},contract='EDAM文件路径相对work_root导出；WIDTH参数和iverilog_options通过flow_options传播至实际编译器。')]
    d['runtime_infrastructure']=[dict(reference='Icarus12.0+make4.3',kind='external_runtime',reason='WSL用户私有目录解包，不改系统；真实编译vvp产物和observed.txt。')]
    d['tasks']=[recipe('repair_missing_core_dependency','把tb依赖错误adder2.0改为已注册1.0后重新解依赖、导出并构建运行。','两个本地core，期望四点[0,3,256,510]固定。',[('注册及解析',['fusesoc.coremanager.CoreManager.add_library','fusesoc.coremanager.CoreManager.get_core','fusesoc.edalizer.Edalizer.run']),('导出和实际执行',['fusesoc.edalizer.Edalizer.export','edalize.flows.sim.Sim.configure','edalize.flows.edaflow.Edaflow.build','edalize.flows.sim.Sim.run'])],['错误实际DependencyError','修复依赖1.0','输出四点匹配'],'verify_fusesoc.py:dependency'),recipe('repair_build_parameter_width','EDAM WIDTH=8导致真实输出截断；恢复9后重建，不修改目标表。','参数错误仍可构建，必须看运行结果。',[('生成EDAM',['fusesoc.edalizer.Edalizer.run','fusesoc.edalizer.Edalizer.export']),('配置并运行',['edalize.flows.sim.Sim.configure','edalize.flows.edaflow.Edaflow.build','edalize.flows.sim.Sim.run']),('修复参数复跑',['edalize.flows.sim.Sim.configure','edalize.flows.edaflow.Edaflow.build','edalize.flows.sim.Sim.run'])],['错误[0,3,0,254]','恢复[0,3,256,510]'],'verify_fusesoc.py:width')]
    # Match the immutable runtime task identifiers exactly.
    d['tasks'][0]['id']='repair_ip_dependency_version'
    d['tasks'][1]['id']='repair_backend_width_parameter'
    c.write(d)

    lg=lambda module,name,methods,cap,why,cons=None:item('laygo2','laygo2.'+module,name,methods,cap,why,cons)
    d=base('03.11.03','通过laygo2的实例模板、栅格、版图数据库和引脚映射构建参数化定制版图：生成对象、放置和布线后导出可复用模板及SKILL文本，使用几何间隔、引脚标签和YAML往返检查修复任务。',[('laygo2','primary','单一模板/栅格/对象体系，避免混入其他PCell引擎重复几何状态。')],[
        c.source('https://github.com/niftylab/laygo2/blob/stable-230804/laygo2/object/grid/placement.py','固定发布源码PlacementGrid.place将抽象坐标映射至实例xy；文档例以实际实例和网格说明放置。',['placement_grid','instance','xy'],['PlacementGrid.place'],['栅格pitch错误导致实例重叠']),
        c.source('https://github.com/niftylab/laygo2/blob/stable-230804/laygo2/object/template/core.py','模板源码说明Native/Parameterized/UserDefined的bbox、pins、generate与netmap，模板到实例是关键状态转移。',['template','pin','netmap','instance'],['NativeInstanceTemplate.generate','Instance.update_netname'],['错误引脚映射修复']),
        c.source('https://github.com/niftylab/laygo2/blob/stable-230804/laygo2/interface/yaml.py','YAML接口把真实模板bbox和pins写出并恢复为TemplateLibrary，适合固定样例往返验收。',['template_library','serialized_bbox','pin_net'],['export_template','import_template'],['220x100nm双实例版图模板往返'])],
        [lg('object.template.core','NativeInstanceTemplate','__init__ bbox pins generate export_to_dict','template','常用固定原语的几何/引脚查询和实例化。'),lg('object.template.core','ParameterizedInstanceTemplate','__init__ bbox pins generate','template','参数驱动原语函数，具体工艺实现为显式外部依赖。'),lg('object.template.core','UserDefinedTemplate','__init__ bbox pins generate','template','自定义生成器入口，不展开内部回调。'),lg('object.grid.core','OneDimGrid','__init__ export_to_dict flip copy concatenate','grid','栅格建立、复制与组合。'),lg('object.grid.core','Grid','__init__ bbox crossing overlap union center copy vflip hflip vstack hstack','grid','保留常用坐标关系/变换，删除四角/宽高属性重复动作。'),lg('object.grid.placement','PlacementGrid','place','place','真实栅格放置入口。','继承已保留Grid.__init__，按PlacementGrid(name,vgrid,hgrid)使用。'),lg('object.grid.routing','RoutingGrid','__init__ route via route_via_track pin','route','局部布线、过孔和引脚生成；当前固定例未实际运行工艺布线。'),lg('object.template.routing','RoutingMeshTemplate','__init__ add_track add_node generate','route','连接多个节点的高层布线模板，删除内部bbox/pins重复查询。'),lg('object.physical','Instance','__init__ update_netname','place','对象原点、bbox、pins为状态；只保留构造与显式网名更新。'),lg('object.physical','Pin','__init__ export_to_dict','place','引脚几何与标签序列化。'),lg('object.physical','Rect','__init__ align','place','金属几何和对齐。'),lg('object.database','BaseDatabase','keys items','database','统一有限查询接口，不给每个派生类复制。','Design/Library构造后获得继承协议。'),lg('object.database','LibraryWrapper','__init__ append','database','实际Library继承的构造/追加。'),lg('object.database','Library',[],'database','顶层库状态对象。','继承LibraryWrapper.__init__；Library(name=...)。'),lg('object.database','Design','__init__ append place route via route_via_track pin export_to_template get_matched_rects_by_layer','database','完整设计对象链，高层路由和模板导出；基础几何函数不额外并列。'),lg('interface.yaml','export_template',None,'io','可复用模板持久化。'),lg('interface.yaml','import_template',None,'io','恢复模板并重生成实例。'),lg('interface.skill','export',None,'io','生成真实SKILL文本；不把导出当作Cadence已执行。')],['template','grid','place','route','database','io'],[dict(name='template_library',identity='libname+cellname',attributes=['bbox','pins','parameters','netmap'],lifecycle='define -> generate -> place -> export template -> reload'),dict(name='layout_design',identity='libname+cellname+objectname',attributes=['grid_pitch','instances','rectangles','pins','net_names'],lifecycle='append -> place -> inspect overlap -> repair -> serialize')],'laygo2',['官方stable-230804源码版本0.5.5与同版本PyPI代码不同；必须从固定Git发布源码安装，PyPI版Design.bbox错误取minimum已实际发现。','固定例使用抽象100x100nm原语和fixture间隔规则，没有代工厂MOS/DRC/LVS。','真实运行placement、pins、YAML往返、SKILL文本导出；未执行Cadence、路由模板或版图电气提取。'])
    d['runtime_infrastructure']=[dict(reference='official laygo2_tech example',kind='fixture_technology',reason='官方发布SKILL模块依赖laygo2_tech；导入固定源码自带示例技术模块并临时切换源目录以解析其相对YAML，不伪造模块或修改源。')]
    d['tasks']=[recipe('repair_grid_pitch_overlap','pitch=15使第二实例x=90产生10nm重叠；修正pitch=20后x=120、间隙20。','100x100nm两实例，固定目标x=0/120。',[('生成模板实例',['laygo2.object.template.core.NativeInstanceTemplate.__init__','laygo2.object.template.core.NativeInstanceTemplate.generate']),('栅格放置',['laygo2.object.grid.core.OneDimGrid.__init__','laygo2.object.grid.placement.PlacementGrid.place']),('修复并导出',['laygo2.object.grid.placement.PlacementGrid.place','laygo2.object.database.Design.export_to_template'])],['错误重叠10nm','修复间隔20nm'],'verify_laygo2.py:pitch'),recipe('repair_pin_net_mapping_and_template_roundtrip','错误网名WRONG修回GATE，导出完整双实例模板，再从YAML恢复并核对bbox与引脚。','固定GATE目标与220x100nm总体bbox。',[('生成并放置实例',['laygo2.object.template.core.NativeInstanceTemplate.generate','laygo2.object.grid.placement.PlacementGrid.place']),('组合设计并导出',['laygo2.object.database.Design.append','laygo2.object.database.Design.export_to_template','laygo2.interface.yaml.export_template']),('恢复和检查',['laygo2.interface.yaml.import_template','laygo2.object.template.core.NativeInstanceTemplate.generate','laygo2.interface.skill.export'])],['pin由WRONG恢复GATE','bbox=[[0,0],[220,100]]','YAML恢复仍为GATE'],'verify_laygo2.py:netmap')]
    c.write(d)

    al=lambda module,name,methods,cap,why,cons=None:item('ALIGN-analoglayout','align.'+module,name,methods,cap,why,cons)
    d=base('03.11.02','围绕ALIGN官方发布的模拟自动版图链组织网表拓扑、层次/约束、mock PDK原语、几何和导出状态。当前可验证任务覆盖反相器拓扑错误修复和电容原语尺寸预算修复，真实生成LEF/GDS并独立读回；完整原生布局布线需额外后端。',[('ALIGN-analoglayout','primary','保留网表到约束/原语/几何/输出的同一体系；同名PyPI align无关，不使用。')],[
        c.source('https://github.com/ALIGN-analoglayout/ALIGN-public/blob/v1.0/align/compiler/read_netlist.py','官方解析器从SPICE提取器件端口、参数与bipartite graph，支持指定top及层次解析。',['netlist','device','terminal_role','net_graph'],['SpiceParser.sp_parser','SpiceParser.resolve_hierarchy'],['NMOS gate误接OUT修回IN']),
        c.source('https://github.com/ALIGN-analoglayout/ALIGN-public/blob/v1.0/align/primitive/main.py','主原语入口根据MOS/Cap/Res选择PDK生成器，输出debug/geometry JSON、LEF和GDS JSON。',['pdk','primitive','parameters','layout_artifact'],['generate_primitive','generate_Cap'],['更正电容参数后重新生成并检查面积']),
        c.source('https://github.com/ALIGN-analoglayout/ALIGN-public/blob/v1.0/align/primitive/default/cap.py','默认电容通过多层交错PLUS/MINUS金属和过孔构成，按PDK栅格量化，Boundary并不等于全部金属外包框。',['wire','via','PLUS','MINUS','boundary'],['CapGenerator.addCap','Canvas.addWire','Canvas.addVia'],['按独立GDS外包框核对1.2um预算'])],
        [al('compiler.read_netlist','SpiceParser','__init__ sp_parser resolve_hierarchy resolve_top_param','netlist','保留高层网表/层次解析，删逐行解析内部入口。'),al('compiler.compiler','generate_hierarchy',None,'constraint','网表到层次/结构匹配高层入口；固定例未完整跑此阶段。'),al('compiler.compiler','compiler',None,'constraint','编译器整合入口，避免保留全部图匹配细节。'),al('compiler.compiler','compiler_output',None,'constraint','编译产物输出。'),al('compiler.write_constraint','FindSymmetry',None,'constraint','模拟匹配的对称约束发现参考。'),al('compiler.write_constraint','FindArray',None,'constraint','阵列约束参考。'),al('compiler.write_constraint','WriteConst',None,'constraint','约束写出。'),al('cell_fabric.pdk','Pdk','__init__ load items keys get_via_stack get_gds_map get_via_table','technology','工艺层/过孔/映射读取；禁止把mock技术叫foundry签核。'),al('primitive.main','generate_primitive',None,'primitive','统一MOS/Cap/Res几何生成和输出，内部各类型函数不重复暴露。'),al('primitive.default.cap','CapGenerator','__init__ addCap','primitive','常用电容原语入口。'),al('primitive.default.mos','MOSGenerator','__init__ addNMOSArray addPMOSArray','primitive','互补MOS阵列参考。'),al('primitive.default.res','ResGenerator','__init__ addResArray','primitive','电阻阵列参考。'),al('cell_fabric.canvas','Canvas','__init__ computeBbox setBboxFromBoundary addGen addWire addRegion addVia addWireAndViaSet pushTr popTr removeDuplicates gen_data writeJSON writeGDS loadPDK checkDesignRules extractParasitics','geometry','核心几何和检查生命周期，删除绘图/ASCII等辅助入口。'),al('cell_fabric.generators','Wire','__init__ segment','geometry','规则金属段。'),al('cell_fabric.generators','Via','__init__ segment','geometry','规则过孔。'),al('cell_fabric.generators','Region','__init__ segment','geometry','边界区域。'),al('cell_fabric.transformation','Transformation','__init__ hit hitRect mult','geometry','层次几何变换，重复pre/post别名裁剪。'),al('cell_fabric.drc','DesignRuleCheck','__init__ run','validate','真实mock DRC检查器，num_errors为状态。'),al('cell_fabric.pex','ParasiticExtraction','__init__ run getSummaryCaps writePex','validate','局部寄生提取参考，未当作电容值实测。'),al('gdsconv.json2gds','convert_GDSjson_GDS',None,'io','真实二进制GDS序列化。'),al('gdsconv.gds2json','convert_GDS_GDSjson',None,'io','GDS恢复为结构化视图。'),al('cell_fabric.lef_to_json','lef_to_json',None,'io','LEF接口数据读取。'),al('main','schematic2layout',None,'flow','完整自动版图入口，明确需要原生PnR后端。'),al('pnr.main','generate_pnr',None,'flow','原生布局布线阶段接口参考，当前未安装或运行。')],['netlist','constraint','technology','primitive','geometry','validate','io','flow'],[dict(name='analog_circuit',identity='top+instance',attributes=['ports','device_models','role_connections','parameters','constraints'],lifecycle='parse -> inspect graph -> repair netlist -> compile constraints'),dict(name='primitive_layout',identity='mock_pdk+block+value',attributes=['terminals','bbox','DRC_errors','LEF','GDS'],lifecycle='load technology -> generate -> deduplicate/check -> export -> independent readback -> repair')],'align',['固定v1.0源码内部版本0.9.8，来源为官方Git发布；PyPI同名align是无关包。','真实实跑SPICE拓扑及mock电容原语两个局部子链；未将反相器完整自动布局，也未调用原生PnR、代工厂PDK或电学仿真。','FinFET14nm_Mock_PDK只是官方教学技术。零mock DRC错误不等于制造签核或实际电容值合格。'])
    d['runtime_infrastructure']=[dict(reference='gdstk1.0.1',kind='independent_oracle',reason='只作为独立GDS读取器验外包框/多边形；不纳入第二套可操作几何状态。'),dict(reference='ALIGN native PnR',kind='external_runtime_unverified',reason='完整schematic2layout/generate_pnr参考接口需要额外原生构建，未实跑。')]
    d['tasks']=[recipe('repair_analog_topology_gate','解析反相器图，发现MN gate误接OUT导致5条边；修复IN后检查两个器件端口角色和6条连接。','固定IN/OUT/VDD/VSS及MN/MP角色，不使用解析结果生成expected。',[('解析网表',['align.compiler.read_netlist.SpiceParser.__init__','align.compiler.read_netlist.SpiceParser.sp_parser']),('修复网表再解析',['align.compiler.read_netlist.SpiceParser.__init__','align.compiler.read_netlist.SpiceParser.sp_parser'])],['MN ports由OUT/OUT/VSS恢复OUT/IN/VSS','MP仍OUT/IN/VDD','共6连接'],'verify_align.py:topology'),recipe('repair_primitive_area_budget','原语参数误为8超出1.2x1.2um固定预算，恢复2后重新生成LEF/GDS并独立读回检查几何与PLUS/MINUS引脚。','预算是外部目标，不能随生成结果变；使用mock PDK。',[('生成原语',['align.primitive.main.generate_primitive']),('检查并输出',['align.cell_fabric.drc.DesignRuleCheck.run','align.gdsconv.json2gds.convert_GDSjson_GDS']),('修复后重新生成',['align.primitive.main.generate_primitive','align.gdsconv.json2gds.convert_GDSjson_GDS'])],['8超出固定预算','2恢复预算内','PLUS/MINUS保持','mock DRC=0且真实GDS有多边形'],'verify_align.py:primitive budget')]
    c.write(d)


if __name__=='__main__':
    main()
