"""Select one Verilog parser/AST/codegen path with native execution evidence."""
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_design_lab_sources import BASE,RAW


def s(module,name,methods,cap,why,construction=None):
    return symbol('pyverilog','pyverilog.'+module,name,methods,cap,why,construction)


def main():
    c=Collection(base=BASE,raw=RAW)
    symbols=[s('vparser.parser','VerilogParser','__init__ parse get_directives get_default_nettype','parse','文本解析和指令查询，裁剪数百p_*语法产生式与内部typecheck。'),s('vparser.ast','Node','children show','inspect','公共遍历与展示协议由所有AST节点继承。','由解析器返回实际节点子类，不直接构造抽象Node。'),s('ast_code_generator.codegen','ASTCodeGenerator','__init__','generate','生成器构造入口，具体visit_*处理器由继承分派自动选择。'),s('ast_code_generator.codegen','ConvertVisitor','visit','generate','ASTCodeGenerator继承的真实visit分派入口，不复制为子类方法。','通过ASTCodeGenerator构造获得。')]
    for name in ['Source','Description','ModuleDef','Paramlist','Portlist','Port','Width','Identifier','Constant','Variable','Ioport','Parameter','Decl','Concat','Repeat','Partselect','Pointer','Lvalue','Rvalue','Operator','UnaryOperator','Cond','Assign','Always','SensList','Sens','Substitution','IfStatement','CaseStatement','Case','Block','Initial','InstanceList','Instance','ParamArg','PortArg']:
        symbols.append(s('vparser.ast',name,'__init__','edit','常用模块、端口、表达式、赋值、控制与层次节点；只保留构造，遍历统一继承Node.children。'))
    for name,base in [('IntConst','Constant'),('Input','Variable'),('Output','Variable'),('Wire','Variable'),('Reg','Variable'),('Plus','Operator'),('Minus','Operator'),('Eq','Operator'),('NonblockingSubstitution','Substitution'),('BlockingSubstitution','Substitution')]:
        symbols.append(s('vparser.ast',name,[],'edit','保留真实语义节点类型供解析/编辑，不重复继承方法。',f'继承pyverilog.vparser.ast.{base}.__init__，源类无独立构造方法；基类已同时保留。'))
    c.write(dict(scenario_id='03.08.02',description='统一采用PyVerilog解析、检查并修改Verilog AST，再生成源码并交实际Icarus编译仿真；环境状态包括模块/端口位宽/表达式依赖和代码版本。以固定输入输出表发现缺失依赖与位宽截断，修复后重新解析和执行。',packages=[('pyverilog','primary','解析、AST编辑与代码生成同一模型，避免跨解析器AST转换。'),('hdlConvertor','excluded','VHDL/SystemVerilog解析范围更广，但当前Verilog任务能力重叠；完整Cython导出候选保留，不引入第二套AST。')],sources=[
        c.source('https://github.com/PyHDI/Pyverilog/tree/1.3.0','固定1.3.0官方正文列出parser/dataflow/controlflow/codegen并展示ModuleDef、端口、赋值、条件、时序节点生成Verilog；完整文件预处理通常要求Icarus。',['source_text','AST','module','port','expression'],['VerilogParser.parse','ASTCodeGenerator','ConvertVisitor.visit'],['解析→编辑→生成→真实仿真闭环']),
        c.source('https://github.com/PyHDI/Pyverilog/blob/1.3.0/examples/example_parser.py','官方解析示例接收include/define并输出ast.show与directives；本地固定例只含无宏文本，直接parse避免虚构预处理执行。',['AST','directive','source_location'],['VerilogParser.parse','Node.show','VerilogParser.get_directives'],['检查信号依赖与声明位宽']),
        c.source('https://github.com/PyHDI/Pyverilog/blob/1.3.0/examples/example_codegen.py','官方示例通过ASTCodeGenerator.visit将解析树生成Verilog文本，区分代码生成与实际仿真；当前另用真实Icarus执行生成工件。',['AST_revision','generated_verilog'],['ASTCodeGenerator','ConvertVisitor.visit'],['修改表达式后生成、重解析、执行固定向量']),
        c.source('https://github.com/PyHDI/Pyverilog/blob/1.3.0/examples/example_dataflow_analyzer.py','官方数据流样例明确terms/binddict与信号/实例查询的关系；当前小例用AST遍历核对直接依赖，不把完整数据流引擎列为已运行。',['signal','data_dependency','module_instance'],['Node.children','Identifier'],['缺失b输入依赖导致错误输出'])],
        entities=[dict(name='verilog_source',identity='design_id+revision',attributes=['source_text','module_name','port_widths','parameters','content_hash'],lifecycle='load -> parse -> edit AST -> generate new revision -> reparse；不修改固定oracle。'),dict(name='ast_node',identity='revision+tree_path',attributes=['node_type','children','identifier','width','operator','source_line'],lifecycle='inspect -> replace expression/width -> emit；改树后重新计算依赖，不复用旧结论。'),dict(name='simulation_run',identity='run_id',attributes=['source_revision','fixed_vectors','compile_status','observed_outputs','first_mismatch'],lifecycle='compile generated Verilog with Icarus -> execute vvp -> compare fixed table；错误/修复为独立工件。')],capabilities=['parse','inspect','edit','generate'],symbols=symbols,bridges=[],runtime_infrastructure=[dict(reference='IcarusVerilog12.0',kind='external_runtime',reason='在用户WSL私有目录解包Ubuntu12.0-2build2，无全局安装；实际iverilog编译与vvp执行生成Verilog。'),dict(reference='python_fixed_vectors_oracle',kind='infrastructure',reason='4组8bit输入对应手算9bit和[0,3,256,510]，与待修复AST独立；递归walk只遍历节点。'),dict(reference='AST_inheritance',kind='construction_protocol',reason='Plus/Output/IntConst等无本地方法的类型使用已保留Operator/Variable/Constant构造；统一遍历Node.children，生成调用继承的ConvertVisitor.visit。')],boundaries=['只验证组合加法器的直接依赖和输出位宽，不代表全SystemVerilog解析、形式等价证明或完整数据流控制流分析。','无宏文本直接VerilogParser.parse；未将文件预处理包装器或hdlConvertor编译宣称已验证。','selected构造节点供后续任务参考，未逐一执行所有节点类型。'],count_exception='操作数略低于50：AST工具以36种构造与统一遍历/生成组成完整固定任务闭环，空方法语义子类不计操作；不为凑数增加重复children或内部grammar/visitor处理器。',tasks=[
            recipe('repair_missing_data_dependency','解析两输入8bit加法器，定位输出表达式漏掉b；以真实AST Plus修复并重生成代码，Icarus执行后恢复四组固定9bit结果。','输入(0,0),(1,2),(255,1),(255,255)，固定expected=[0,3,256,510]。',[('解析和检查依赖',['pyverilog.vparser.parser.VerilogParser.__init__','pyverilog.vparser.parser.VerilogParser.parse','pyverilog.vparser.ast.Node.children']),('替换右值表达式',['pyverilog.vparser.ast.Identifier.__init__','pyverilog.vparser.ast.Plus','pyverilog.vparser.ast.Rvalue.__init__']),('生成重解析并交实际仿真器',['pyverilog.ast_code_generator.codegen.ASTCodeGenerator.__init__','pyverilog.ast_code_generator.codegen.ConvertVisitor.visit','pyverilog.vparser.parser.VerilogParser.parse'])],['错误依赖只有a','错误输出[0,1,255,255]','修复依赖a,b','实际仿真等于固定表'],'verify_ast.py:missing dependency'),
            recipe('repair_output_width_truncation','定位8bit输出截断进位，将声明宽度改为9bit；生成并重解析后实际编译仿真，恢复256和510。','固定两8bit输入，正确输出必须容纳9bit和；目标表不修改。',[('解析查找Output宽度',['pyverilog.vparser.parser.VerilogParser.parse','pyverilog.vparser.ast.Node.children','pyverilog.vparser.ast.Output']),('替换Width为[8:0]',['pyverilog.vparser.ast.IntConst','pyverilog.vparser.ast.Width.__init__']),('生成复验',['pyverilog.ast_code_generator.codegen.ASTCodeGenerator.__init__','pyverilog.ast_code_generator.codegen.ConvertVisitor.visit','pyverilog.vparser.parser.VerilogParser.parse'])],['错误输出[0,3,0,254]','修复宽度9','实际仿真[0,3,256,510]'],'verify_ast.py:width truncation')],runtime_report=(BASE/'runtime/ast/03.08.02.json').as_posix(),runtime_scope='PyVerilog1.3.0实际parse/edit/codegen，WSL Icarus12.0实际编译与vvp运行，两个正常/错误/修复固定任务。'))


if __name__=='__main__':
    main()
