"""Explicit geometry, DRC and connectivity cuts from the pinned native API."""
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_design_lab_sources import BASE,RAW


def s(name,methods,cap,why,construction=None):
    return symbol('klayout','klayout.db',name,methods,cap,why,construction)


def main():
    c=Collection(base=BASE,raw=RAW)
    layout=c.source('https://www.klayout.org/klayout-pypi/overview/layout/','官方PyPI文档解释Layout读写、dbu微米单位与整数几何的关系、默认1nm精度和编辑已有形状时的editable模式。',['layout','dbu','cell','revision'],['Layout.read','Layout.write','Layout.create_cell'],['往返文件、修复DBU单位而保持几何目标'])
    shapes=c.source('https://www.klayout.org/klayout-pypi/overview/shapes/','每单元/逻辑层持有Shapes，可insert/each/erase；Shape是数据库代理，工作几何对象为Box/Polygon，修改已有数据库须使用editable模式。',['cell','layer','shape'],['Cell.shapes','Shapes.insert','Shapes.each'],['构造矩形层、检测并修复缺失或重叠几何'])
    regions=c.source('https://www.klayout.org/klayout-pypi/overview/geometry/regions/','Region以整数单位多边形支持合并、尺寸偏置、AND/NOT/XOR；由层次begin_shapes_rec读取，DRC功能对应Region方法。',['region','integer_units','marker'],['Region','Region.merged','Region.and_','Region.width_check'],['面积/交集不变量和规则违规定位'])
    drc=c.source('https://github.com/KLayout/klayout/blob/v0.30.12/src/doc/doc/manual/drc_basic.xml','官方固定发布文档正文可读，演示门宽、金属宽/间距、布尔派生层、EdgePairs违规标记和浮点微米/整数DBU差别；本任务使用同原生核心的Python Region入口。',['rule','derived_layer','edge_pair','threshold'],['Region.width_check','Region.space_check','EdgePairs.count'],['最小宽度与间距违规修复，不豁免规则'])
    intro=c.source('https://github.com/KLayout/klayout/blob/v0.30.12/src/doc/doc/manual/lvs_intro.xml','固定发布官方教程以双晶体管反相器介绍几何派生层、器件提取、金属/via连接、SPICE参考与compare；明确本批只完成物理连通提取，非完整MOS LVS。',['conductive_layer','via','net','reference_topology'],['LayoutToNetlist.connect','LayoutToNetlist.extract_netlist'],['发现漏via或多余桥造成断短路'])
    connect=c.source('https://github.com/KLayout/klayout/blob/v0.30.12/src/doc/doc/manual/lvs_connect.xml','官方正文说明同层接触岛、跨层connect重叠连接、标签命名及global/implicit/soft连接的不同语义；任务避免用强制join掩盖实际缺口。',['metal_island','via','net','probe_point'],['LayoutToNetlist.register','LayoutToNetlist.connect','LayoutToNetlist.probe_net'],['按固定A-B连通且C独立目标修复实际几何'])
    common=[s('Box','__init__ area width height bbox contains overlaps transformed','geometry','基本整数矩形及独立边长/面积观测。'),s('Region','__init__ insert clear each count area bbox merged and_ or_ not_ xor','geometry','统一多边形状态、布尔运算与量测，避免引入另一套几何数据库。')]
    io=[s('Layout','__init__ create_cell layer find_layer get_info each_cell cell top_cell read write','database','单一数据库所有权、层映射、单元查找和持久化。'),s('Cell','cell_index shapes insert each_inst begin_shapes_rec bbox flatten','database','层次单元及其形状/实例；由Layout.create_cell获取，不暴露原生生命周期方法。','由已选Layout.create_cell/cell/top_cell返回；不自行分配孤立Cell。'),s('Shapes','insert each erase size clear','database','经Cell.shapes取得的层内形状容器。','由Cell.shapes返回，不直接构造。')]
    base=dict(packages=[('klayout','primary','统一整数层次数据库、几何、规则检查及连通提取，原生Python接口保持同一DBU。'),('gdstk','excluded','GDS/OASIS与几何布尔能力重叠；完整原生候选池已保留，当前选择KLayout避免双数据库/单位和重复工具。')],
        bridges=[],runtime_infrastructure=[dict(reference='fixed_geometry_topology_oracle',kind='infrastructure',reason='固定矩形边长/间距、DBU平方换算与手写A-B连通/C独立关系；不替代KLayout原生几何、DRC或连通提取。')],
        boundaries=['klayout.de在线页面返回200 challenge，未计有效研究；采用官方klayout.org PyPI教程与固定发布源码文档正文。','完整原生候选由官方core.pyi提取，当前只裁剪常用闭环方法；原生数据属性dbu/坐标/cluster_id作为状态，不伪造函数。','未验证所有精选API，只实跑两条固定任务；完整Agent状态隔离和版本失效封装仍待后续。'])
    for sid in ['03.02.01','03.02.02','03.02.03']:
        d=dict(base,scenario_id=sid,runtime_report=(BASE/f'runtime/klayout/{sid}.json').as_posix(),runtime_scope='KLayout0.30.12真实原生几何/DRC/连通提取，固定矩形和拓扑独立oracle；无GUI或代工厂PDK。')
        if sid=='03.02.01':
            d.update(description='使用KLayout建立带DBU/层号/层次实例的版图数据库，执行矩形与多边形布尔操作、GDS/OASIS持久化和层次面积检查；以固定尺寸和单位目标发现错误并修复。GDSTK作为重叠替代候选保留但不重复暴露。',sources=[layout,shapes,regions],capabilities=['geometry','database','placement'],symbols=common+io+[
                s('Trans','__init__ inverted trans','placement','整数平移/旋转/镜像变换；保持DBU契约。'),s('CellInstArray','__init__ bbox each_trans size','placement','引用已有单元的实例/阵列，避免复制展开原始几何。'),s('Point','__init__ distance to_dtype','geometry','整数点与微米表示转换。'),s('Polygon','__init__ area bbox each_point_hull insert_hole transformed','geometry','非矩形和孔洞的必要建模扩展，不纳入复杂三角化/内部内存API。')],
                entities=[dict(name='layout',identity='layout_id',attributes=['dbu_um','layers(number,datatype)','cell_index','source_revision','file_format'],lifecycle='create/read -> register layer/cell -> edit -> write -> read back/check；修改后旧导出失效。'),dict(name='cell_geometry',identity='cell_index+layer_index',attributes=['integer_shapes','instance_transforms','hierarchy','bbox_dbu','area_um2'],lifecycle='construct shape -> insert/reference -> transform/boolean -> measure；DBU变化必须重算物理量。')],tasks=[
                    recipe('hierarchical_layout_roundtrip','创建1nm DBU布局与1µm×0.5µm子单元，两次平移实例化；写GDS/OASIS并重读，核对两个单元、层次边界框和总面积1µm²。','两引用分别平移(2,1)µm与(4,1)µm。',[('构造层次数据库',['klayout.db.Layout.__init__','klayout.db.Layout.create_cell','klayout.db.Layout.layer','klayout.db.Box.__init__','klayout.db.Cell.shapes','klayout.db.Shapes.insert','klayout.db.CellInstArray.__init__','klayout.db.Trans.__init__','klayout.db.Cell.insert']),('持久化后重新观察',['klayout.db.Layout.write','klayout.db.Layout.read','klayout.db.Layout.each_cell','klayout.db.Cell.begin_shapes_rec','klayout.db.Region.__init__','klayout.db.Region.area','klayout.db.Region.bbox'])],['2个cell/2个instance','bbox DBU=[2000,1000,5000,1500]','面积=1µm²','两文件往返dbu和几何一致'],'verify_klayout.py:geometry'),
                    recipe('repair_layout_units_and_overlap','将误设0.01µm的DBU恢复0.001µm，以固定1µm²目标验收；另对两半重叠矩形执行并/交运算，验证0.75/0.25µm²。','原整数几何不变，错误DBU产生100µm²。',[('检查物理面积与布局单位',['klayout.db.Region.area','klayout.db.Layout.top_cell']),('恢复DBU状态后检查布尔区域',['klayout.db.Box.__init__','klayout.db.Region.__init__','klayout.db.Region.or_','klayout.db.Region.merged','klayout.db.Region.and_','klayout.db.Region.area'])],['100µm²拒绝→1µm²','并集750000DBU²','交集250000DBU²'],'verify_klayout.py:geometry wrong/fixed'),
                ])
        elif sid=='03.02.02':
            d.update(description='以KLayout Region统一表示规则输入层和派生层，按固定最小线宽/间距生成真实EdgePairs违规标记；修改原始几何并重跑检查，保留规则阈值和单位作为不可偷改的验收条件。',sources=[layout,regions,drc],capabilities=['geometry','database','rules','markers'],symbols=common+io+[
                s('EdgePairs','count each bbox polygons write','markers','实际违规边对的计数/定位/保存，不只返回布尔通过状态。','由Region规则检查返回。'),s('Trans','__init__ trans','geometry','重放固定几何变换。')]+[
                # One source symbol per profile; extend Region below instead of duplicate it.
            ],entities=[dict(name='rule_deck',identity='deck_id',attributes=['dbu','minimum_width','minimum_spacing','layer_bindings','revision'],lifecycle='load -> freeze acceptance thresholds -> run；修复只改设计几何，不改变验收阈值。'),dict(name='layout_region',identity='layer_id+geometry_revision',attributes=['rectangles','width_dbu','gap_dbu','derived_region'],lifecycle='construct -> check -> inspect marker -> revise -> rerun。'),dict(name='violation_markers',identity='run_id+rule_id',attributes=['edge_pairs','bbox','count','geometry_revision'],lifecycle='Region check -> inspect/write -> invalidate after geometry edit。')],tasks=[
                    recipe('repair_minimum_width','在1nm DBU下检查两条宽120nm、间距150nm的金属线；将宽度80nm变体定位为违规并恢复120nm，保持100nm规则阈值。','固定线长1000nm，两条平行矩形。',[('构造正常和错误几何',['klayout.db.Box.__init__','klayout.db.Region.__init__','klayout.db.Region.insert']),('运行宽度规则并定位标记',['klayout.db.Region.width_check','klayout.db.EdgePairs.count']),('修改几何后重验',['klayout.db.Region.clear','klayout.db.Region.insert','klayout.db.Region.width_check'])],['正常0违规','80nm时marker>0','恢复120nm后0违规'],'verify_klayout.py:drc width'),
                    recipe('repair_minimum_spacing','固定120nm线宽，发现80nm线间距小于100nm规则；将间距恢复150nm，重新运行空间检查并验证违规归零。','先通过正常样例，再运行只改变gap的错误样例。',[('重建固定长度/线宽的区域',['klayout.db.Box.__init__','klayout.db.Region.__init__','klayout.db.Region.insert']),('检查间距并修复',['klayout.db.Region.space_check','klayout.db.EdgePairs.count','klayout.db.Region.clear','klayout.db.Region.insert']),('同阈值复验',['klayout.db.Region.space_check','klayout.db.EdgePairs.count'])],['80nm间距marker>0','150nm间距marker=0','规则仍100nm'],'verify_klayout.py:drc space'),
                ])
            d['symbols']=[dict(x,capability='rules',methods=x['methods']+'width_check space_check separation_check enclosed_check overlap_check grid_check sized'.split()) if x['name']=='Region' else x for x in d['symbols']]
            d['boundaries']=base['boundaries']+['仅固定两线100nm规则；不是完整工艺签核DRC，未执行Ruby runset或GUI。']
        else:
            d.update(description='以KLayout真实LayoutToNetlist从金属/via多边形提取连通网络，按固定探针与目标拓扑发现漏via断路或多余金属桥短路，修复几何后重新提取并保存l2n结果。验证范围为物理连通，不包括MOS器件提取或完整晶体管LVS。',sources=[layout,regions,intro,connect],capabilities=['geometry','extract','inspect','persist'],symbols=common+[
                s('Point','__init__ distance','geometry','探针固定坐标，独立于提取的网名。'),s('LayoutToNetlist','__init__ register connect extract_netlist netlist probe_net layer_by_name layer_names polygons_of_net each_error is_extracted reset_extracted write read','extract','真实金属/via连接和网络提取主接口；排除强制join与复杂器件提取。'),s('Netlist','circuit_by_name each_circuit top_circuit to_s write','persist','提取产物的电路选择、序列化和持久化。','由LayoutToNetlist.netlist返回。'),s('Circuit','each_net net_by_name nets_by_name net_by_cluster_id each_pin pin_count','inspect','按名称/cluster选择和枚举实际网，保留pin观测，排除修改目标拓扑的join。','由Netlist.circuit_by_name或each_circuit返回。'),s('Net','qname each_pin each_terminal pin_count terminal_count is_floating','inspect','网内端点和悬空属性，cluster_id为状态属性。','由Circuit.each_net或LayoutToNetlist.probe_net返回。')],entities=[dict(name='conductive_layers',identity='layer_id',attributes=['metal1','metal2','via','geometry_revision','dbu'],lifecycle='construct -> register -> connect -> extract；任何几何/连接规则修改使旧netlist失效。'),dict(name='extracted_netlist',identity='extraction_id',attributes=['circuit','nets','cluster_ids','probe_membership','source_revision','l2n_path'],lifecycle='extract -> probe/compare -> write；修复后用新extractor重提取。'),dict(name='topology_target',identity='target_id',attributes=['A=(500,50)','B=(2500,50)','C=(4500,50)','A-B connected','A-C disconnected','expected_nets=2'],lifecycle='load fixed -> compare each extraction；不得用join/global连接掩盖几何缺陷。')],tasks=[
                    recipe('repair_missing_via_open','建立两层金属及跨层via，验证A-B连通而C独立的两网布局；删除B侧via导致三网断路后恢复via，重新提取并确认固定拓扑。','固定三块metal1、一个metal2桥和两via。',[('登记几何和连接规则',['klayout.db.Region.__init__','klayout.db.Region.insert','klayout.db.Box.__init__','klayout.db.LayoutToNetlist.__init__','klayout.db.LayoutToNetlist.register','klayout.db.LayoutToNetlist.connect']),('提取与探针判定',['klayout.db.LayoutToNetlist.extract_netlist','klayout.db.LayoutToNetlist.netlist','klayout.db.Netlist.circuit_by_name','klayout.db.Circuit.each_net','klayout.db.Point.__init__','klayout.db.LayoutToNetlist.probe_net']),('恢复via后重提取保存',['klayout.db.Region.insert','klayout.db.LayoutToNetlist.extract_netlist','klayout.db.LayoutToNetlist.write'])],['正常2网且AB=True/AC=False','缺via3网且AB=False','恢复2网且固定关系通过'],'verify_klayout.py:connectivity open'),
                    recipe('repair_extra_bridge_short','加入连接C的多余metal2桥和via，观察三点并入一个网；移除多余桥后重建提取，恢复2网及A-C隔离。','目标拓扑保持AB连通、C独立。',[('提取带多余桥的布局',['klayout.db.Region.insert','klayout.db.LayoutToNetlist.register','klayout.db.LayoutToNetlist.connect','klayout.db.LayoutToNetlist.extract_netlist']),('用固定探针发现短路',['klayout.db.LayoutToNetlist.probe_net','klayout.db.Circuit.each_net']),('重建正确层并提取保存',['klayout.db.Region.clear','klayout.db.Region.insert','klayout.db.LayoutToNetlist.extract_netlist','klayout.db.LayoutToNetlist.write'])],['错误1网且AC=True','修复2网且AB=True/AC=False'],'verify_klayout.py:connectivity short'),
                ])
        c.write(d)


if __name__=='__main__':
    main()
