"""HDL21/VLSIR structural environments with explicit no-SPICE boundary."""
from copy import deepcopy
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
from seed_gen.scripts.prepare_design_lab_sources import BASE,RAW


def h(module,name,methods,cap,why,construction=None):
    return symbol('hdl21','hdl21.'+module,name,methods,cap,why,construction)


def v(module,name,methods,cap,why,construction=None):
    return symbol('vlsirtools','vlsirtools.'+module,name,methods,cap,why,construction)


def main():
    c=Collection(base=BASE,raw=RAW)
    sources=[c.source('https://github.com/dan-fritchman/Hdl21/blob/v6.0.0/readme.md','官方固定6.0.0教程区分Module/Signal/Instance、两次调用的参数与连接、Generator/paramclass及ExternalModule；物理器件必须映射到PDK或显式外部模块。',['module','signal','instance','parameter','external_model'],['Module','Port','ExternalModule.__call__','to_proto'],['手写拓扑目标、连接修复及参数比例验证']),c.source('https://github.com/dan-fritchman/Hdl21/blob/v6.0.0/examples/idac.py','官方IDAC源例用MOS参数和层次模块构造电流源/DAC单元；几何参数与节点连接是可独立检查的结构状态，不把结构导出等同模拟电流精度。',['MOS','gate_connection','width','length','hierarchy'],['Module','Nmos','Port'],['两管镜像门极接错/尺寸比修复']),c.source('https://github.com/dan-fritchman/Hdl21/blob/v6.0.0/examples/diff_ota.py','官方差分OTA例展示可复用模块/信号与参数化晶体管连接；提示拓扑结构可先于外部仿真检查。',['differential_net','bias','instance_parameters'],['Module','Signal','ExternalModule'],['参数和节点不变量的结构任务']),c.source('https://github.com/Vlsir/Vlsir/blob/v6.0.0/readme.md','官方VLSIR定义circuit/layout/simulation protobuf Schema，Python bindings与VLSIRTools分层；后者提供SPICE/Verilog网表和外部仿真驱动。',['package','module','instance','connection','protobuf_bytes'],['to_proto','from_proto','netlist'],['Schema序列化往返与悬空信号引用修复']),c.source('https://github.com/Vlsir/Vlsir/blob/v6.0.0/VlsirTools/readme.md','官方说明sim输入/输出Schema与实际Spectre/Xyce/Ngspice后端是另一层；netlisting小节未完成，实际网表行为以固定tag源实现及执行证据核对。',['netlist_format','external_backend','simulation_input'],['netlist','NetlistFormat'],['区分原语映射错误和未运行的SPICE求解'])]
    symbols=[h('module','Module','__init__ add get bundle_ports','construct','模块容器及命名信号/实例入口。'),h('module','module',None,'construct','声明式模块装饰器。'),h('signal','Signal',[],'connect','内部信号状态，width/name/visibility/direction字段。','@datatype生成构造；Signal(name=...,width=...)，保留字段契约而不伪造源__init__。'),h('external_module','ExternalModule','__call__','construct','显式模型接口，调用设置参数，端口/模型类型为状态。','@datatype生成构造，字段name/port_list/paramtype/domain/spicetype见原始类源码；运行固定NMOS外部模型。'),h('external_module','ExternalModuleCall',[],'connect','参数化模型与连接调用分离，避免把参数当网络。','由ExternalModule.__call__返回；@calls_instantiate动态附加__call__(**kwargs)返回Instance并连接，动态方法不伪造进AST候选。'),h('instance','Instance','__init__','connect','实例容器和of/conns/name状态；显式构造转发真实基类参数。'),h('instance','InstanceArray','__init__','connect','同一单元阵列与广播连接。'),h('concat','Concat','__init__','connect','连接总线片段，位宽作为派生状态。'),h('bundle','Bundle','__init__ add get','connect','成组信号接口，保留构造与属性增查。'),h('bundle','BundleInstance','__init__','connect','实例化成组接口。'),h('bundle','AnonymousBundle','__init__ add get','connect','按名绑定已有信号为匿名接口。'),h('props','Properties','set get remove','inspect','附加结构注释和设计约束状态。'),h('generator','Generator','__call__','generate','参数化模块调用与缓存入口。','由generator装饰器构造，func/paramtype/enable_cache为@datatype字段。'),h('generator','GeneratorCache','reset','generate','参数化生成器缓存重置，用于独立任务隔离。','零参数构造沿用object.__init__，源类无显式构造。'),h('prefix','Prefixed','new scale','parameter','物理量前缀构造和缩放，避免米/微米混淆。','由new或to_prefixed返回，@datatype字段number/prefix。'),h('prefix','Prefix','from_exp closest','parameter','十进制单位前缀选择；枚举值不作为普通构造。','枚举成员或from_exp/closest返回。'),v('netlist.fmt','NetlistFormat','get to_proto from_proto','export','网表格式解析和Schema枚举互转；不直接暴露内部writer。','Enum成员或get返回。'),v('spicetype','SpiceType','to_schema from_schema','export','MOS/SUBCKT等外部元件语义与Schema对应。','使用SpiceType.MOS等枚举值，不虚构构造。')]
    for name in ['Input','Output','Inout','Port','Power','Ground','PowerGround','Clock']:
        symbols.append(h('signal',name,None,'connect','常用方向/电源/时钟信号工厂，输出Signal状态。'))
    for module,name,cap,why in [('bundle','bundle','connect','声明成组接口。'),('bundle','bundlize','connect','将命名信号构造成组连接。'),('bundle','flipped','connect','翻转成组端口方向。'),('params','paramclass','parameter','定义参数类型与默认值。'),('params','descriptions','parameter','读取参数说明。'),('params','default_instance','parameter','创建默认参数实例。'),('params','default_dict','parameter','导出默认值字典。'),('params','isparamclass','parameter','验证参数类型。'),('generator','generator','generate','将类型注解函数定义为模块生成器。'),('generator','validate','generate','检查生成函数参数和返回Module契约。'),('prefix','to_prefixed','parameter','数值转带单位前缀量。'),('scalar','to_scalar','parameter','归一化可用标量。'),('elab.elab','elaborate','inspect','展开模块、接口、数组并执行结构检查。'),('flatten','flatten','inspect','层次网表展开为平坦模块。'),('flatten','is_flat','inspect','查询是否仍含层次。'),('proto.exporting','to_proto','export','HDL21对象导出VLSIR电路Package。'),('proto.importing','from_proto','export','VLSIR电路重建HDL21命名空间。'),('netlisting','netlist','export','便捷导出网表，复杂任务直接调用VLSIRTools以明确边界。')]:
        symbols.append(h(module,name,None,cap,why))
    symbols += [v('netlist.main','netlist',None,'export','实际统一SPICE/Verilog网表输出；当前opts必须None。'),v('netlist.main','netlist_from_proto',None,'export','由NetlistInput Schema输出网表。')]
    base=dict(packages=[('hdl21','primary','统一参数、信号、模块/实例和展开；保留一个原理图对象模型。'),('vlsirtools','complement','使用共同VLSIR Schema导出网表和验证引用，补足持久化边界。'),('skidl','excluded','元件/网络/原理图创建和ERC重叠；偏PCB库的另一套对象不混入晶体管结构任务。')],sources=sources,entities=[dict(name='schematic',identity='design_id+revision',attributes=['module_name','ports','signals','instances','connection_table','parameter_values'],lifecycle='declare -> instantiate -> connect -> elaborate -> export；修改后构建新对象，固定目标连接表不变。'),dict(name='device_model',identity='domain+model_name',attributes=['ordered_ports','spicetype','parameter_type','width_m','length_m'],lifecycle='explicit interface -> parameter call -> connected instance；未提供工艺模型，仅结构fixture。'),dict(name='circuit_schema',identity='source_revision+package_hash',attributes=['modules','instances','connections','parameters','protobuf_bytes'],lifecycle='to_proto -> serialize -> parse -> netlist；引用必须指向本模块已定义信号。'),dict(name='netlist_artifact',identity='run_id+format',attributes=['SPICE text','port_order','model_names','errors','source_revision'],lifecycle='generate -> inspect -> compare independently specified topology；无求解结果状态。')],capabilities=['construct','connect','parameter','generate','inspect','export'],symbols=symbols,bridges=[dict(from_package='hdl21',to_package='vlsirtools',via='vlsir.circuit.Package',contract='hdl21.to_proto输出真实VLSIR Package；vlsirtools.netlist接收同一Schema，端口名/连接目标/参数与模型类型不能在转换时丢失。')],runtime_infrastructure=[dict(reference='generated_hdl21_constructors',kind='construction_protocol',reason='@datatype/@paramclass由Pydantic生成Signal/ExternalModule等构造；ExternalModuleCall与Module由calls_instantiate添加实例连接调用；Instance的connect/replace/disconnect实际继承私有_Instance，当前候选不伪造继承方法，固定修复重建Module。'),dict(reference='vlsir.circuit_pb2.Package',kind='schema_infrastructure',reason='官方vlsir6.0.0生成protobuf消息持有数据；SerializeToString/ParseFromString/CopyFrom为基础序列化协议，未伪装成vlsirtools源函数。'),dict(reference='python_topology_oracle',kind='infrastructure',reason='手写ref/output两管d/g/s/b连接表及W比2，独立于HDL21自动导出结果；StringIO仅接收实际netlist输出。')],boundaries=['只验证晶体管拓扑、尺寸参数与Schema/网表，不提供真实PDK模型或运行SPICE，尺寸比2不能宣称模拟电流比2。','选择最新可核对稳定源码tag6.0.0组合；PyPI7.0.0与Git稳定标签不一致保留证据，Python3.11匹配pandas1.5依赖。','NetlistOptions接口当前未实现，未选择；内部writer、原语映射和逐节点导出方法不作为额外工具。','参数生成、bundle和flatten等参考工具未逐项执行；固定任务确实覆盖Module/Port/ExternalModule/to_proto和实际网表输出。'])
    for sid in ['03.04.01','03.04.02']:
        d=deepcopy(base)
        d.update(scenario_id=sid,runtime_report=(BASE/f'runtime/schematic/{sid}.json').as_posix(),runtime_scope='HDL21/VLSIR/VLSIRTools6.0.0真实对象展开、SPICE网表与protobuf往返；两个正常/错误/修复固定结构任务，未执行模拟求解。')
        setup=['hdl21.module.Module.__init__','hdl21.signal.Port','hdl21.external_module.ExternalModule','hdl21.external_module.ExternalModule.__call__','hdl21.external_module.ExternalModuleCall']
        export=['hdl21.proto.exporting.to_proto','vlsirtools.netlist.main.netlist']
        if sid=='03.04.01':
            d['description']='构造参数化晶体管级原理图，统一管理端口、信号、实例与尺寸，展开后对固定拓扑表和尺寸比例进行结构验收；门极误接或宽度错误需修改设计并重导出。外部SPICE求解是明确的后续边界。'
            d['tasks']=[recipe('repair_current_mirror_gate_connection','构造两管NMOS镜像拓扑，将输出管误连out的门极恢复iin，重新导出后逐端口匹配固定表，并恢复完全相同的SPICE网表。','端口iin/out/vss，ref.d/g=iin，output.d=out,g=iin，双方s/b=vss。',[('声明并连接两管',setup),('导出检查手写连接表',export),('重建正确连接并复验',setup+export)],['2实例3端口','错误output.g=out被固定表拒绝','修复门极iin','修复网表与正常相同'],'verify_schematic.py:gate connection'),recipe('repair_transistor_sizing_ratio','保持参考管W=1µm、L=180nm，发现输出管W=3µm使尺寸比3，恢复W=2µm后重新导出并断言比值2。','仅要求几何尺寸比2，不用尺寸比例冒充真实镜像电流性能。',[('构造带明确尺寸的外部模型',setup),('导出参数核对比例',export),('修复宽度重建输出',setup+export)],['错误宽度比3拒绝','修复宽度比2','连接表不变','网表与正常相同'],'verify_schematic.py:sizing')]
        else:
            d['description']='将HDL21层次电路转换为VLSIR Schema并输出SPICE网表，管理外部器件映射、序列化字节和信号引用；定位未映射物理原语与悬空引用，修复后要求结构表和网表文本保持一致。'
            d['symbols'] += [h('primitives','Nmos',None,'construct','生成通用NMOS参数调用，故意未映射会触发真实网表错误；修复使用显式ExternalModule。')]
            d['tasks']=[recipe('repair_unmapped_physical_primitive','对通用Nmos直接网表化观察实际未映射物理原语错误，以端口/模型类型明确的ExternalModule替代，恢复相同镜像拓扑。','固定两管连接表不变，初始Nmos无PDK映射。',[('构造未映射原语',['hdl21.primitives.Nmos','hdl21.module.Module.__init__','hdl21.signal.Port']),('展开并尝试输出',export),('用显式NMOS外部接口修复',setup+export)],['真实RuntimeError要求PDK或ExternalModule','修复网表成功','固定连接表仍满足'],'verify_schematic.py:physical primitive'),recipe('repair_schema_signal_reference','将Package序列化并读回，核对网表一致；把output.g目标改成不存在的missing_gate_net触发实际引用错误，恢复iin后重输出。','正常Schema来源为固定镜像电路，protobuf只是持久化，不修改oracle。',[('生成并输出正常Schema',setup+export),('序列化往返后按同Schema输出',['vlsirtools.netlist.main.netlist']),('定位未知信号，恢复引用后再次输出',['vlsirtools.netlist.main.netlist'])],['真实protobuf往返网表相同','missing_gate_net触发Unknown signal','恢复iin后网表完全相同'],'verify_schematic.py:schema reference')]
        c.write(d)


if __name__=='__main__':
    main()
