"""Detectorintegration, reciprocalspace, XRRfit and crystalreference selections."""
from pathlib import Path
from seed_gen.scripts.scenario_collection_support import Collection,symbol,recipe
BASE=Path('seed_gen/scenario_collection/l1_metrology_quality');RAW=Path('seed_gen/pypi_outputs/ori_all_funcs/scenario_collection/l1_metrology_quality')
def cl(p,m,n,methods,cap,why,construction=None):return symbol(p,m,n,methods,cap,why,construction)
def fn(p,m,names,cap,why):
    if m=='xrayutilities.utilities':m='xrayutilities.utilities_noconf'
    return [symbol(p,m,n,None,cap,why) for n in names.split()]
def crystal():return [cl('xrayutilities','xrayutilities.materials.material','Crystal','__init__ fromCIF toCIF Q HKL planeDistance chemical_composition StructureFactor StructureFactorForHKL ApplyStrain','material','晶体参考、倒易矢量和允许的简单结构因子，保留空间群/单位。'),cl('xrayutilities','xrayutilities.materials.spacegrouplattice','SGLattice','__init__ base ai B GetPoint GetQ GetHKL UnitCellVolume hkl_allowed get_allowed_hkl ApplyStrain equivalent_hkls','lattice','晶格参数与实/倒易坐标映射，不将角度校准和晶格模型混合。')]
def main():
    c=Collection(base=BASE,raw=RAW);F='http://www.silx.org/doc/pyFAI/latest/';X='https://xrayutilities.sourceforge.io/';D='https://www.diffpy.org/diffpy.structure/'
    ev={F+'usage/cookbook/integration_with_python.html':'实际Eiger4M Al2O3图+PONI标定教程，将图像、几何、dark/flat输入结合进行一/二维方位积分。',F+'usage/tutorial/Introduction/introduction.html':'ESRF衍射图分析教程强调探测器图像显示/方向决定方位角符号，并以真实图像和几何做可复现计算。',F+'geometry.html':'PONI六参数几何明确距离、法向入射位置、旋转及波长；ndarray[y,x]与poni1/2分别慢/快轴。',X+'examples.html':'实际Panalytical XRDML、SPEC/EDF与Si/GaAs示例，从角度映射Q和网格化；角度/波长和样品方向必须绑定。',X+'simulations.html':'实际层系统XRR/XRD示例定义Layer厚度Angstrom、density kg/m3和层序；Parratt反射模型与lmfit参数约束拟合薄膜。',X+'xrayutilities.html':'官方API列出HXRD/QConversion、晶体Q/HKL、Gridder和文件入口，按固定发布定义作为参数/返回核查。',D+'mod-lattice.html':'Lattice以Angstrom长度及度数角度构造，演示笛卡尔/分数坐标、体积和倒易度量；单位不能从数值自动推断。',D+'mod-atom.html':'Atom保存元素、分数/笛卡尔位置、占据和位移参数，label形成结构内稳定引用。',D+'api/diffpy.structure.html':'结构容器load_structure读CIF/XYZ并可保存，官方3.5推荐snake_case，结构解析不等于散射反演。','https://lmfit.github.io/lmfit-py/examples/example_fit_with_bounds.html':'给制造信号设置具名参数min/max后拟合，边界和残差必须一起验收；退出成功不自动证明目标厚度恢复。'}
    def src(urls):return [c.source(u,ev[u],['sample','geometry','axis_unit','crystal','layer_stack'],['load','calibrate','transform','simulate','fit','persist'],['固定几何/晶格和独立物理公式的分析、诊断与修复']) for u in urls]
    def task(sid,tid,desc,initial,steps,checks):return recipe(tid,desc,initial,steps,checks,'verify_xrd.py:'+sid)
    designs=[dict(scenario_id='07.05.01',description='从二维XRD探测器像素、PONI几何、波长、掩膜和dark/flat校正生成带单位的一维/二维积分结果；参数与原图共同构成状态，几何变化需重算。固定环形图以独立atan几何及常量图强度守恒验收。',packages=[('pyFAI','primary','唯一方位积分/探测器几何实现；不把FabIO依赖当已搜集领域包。')],
      symbols=[cl('pyFAI','pyFAI.integrator.azimuthal','AzimuthalIntegrator','integrate1d integrate2d_ng integrate_radial','integrate','高层积分主入口，显式单位/校正/算法与分箱。','继承Integrator.__init__，通过AzimuthalIntegrator构造。'),cl('pyFAI','pyFAI.integrator.common','Integrator','__init__ reset create_mask dark_correction flat_correction save1D save2D darkcurrent flatfield','preprocess','积分器继承构造、dark/flat/mask和数据导出。','从AzimuthalIntegrator继承，避免旧版integrate1d_legacy重复入口。'),cl('pyFAI','pyFAI.geometry.core','Geometry','get_config set_config save load getPyFAI setPyFAI twoThetaArray qArray chiArray solidAngleArray polarization reset dist poni1 poni2 rot1 rot2 rot3 wavelength pixel1 pixel2','geometry','探测器物理几何、单位轴和PONI持久化；变更后旧积分失效。','由积分器继承，Geometry不独立构造第二套状态。'),cl('pyFAI','pyFAI.detectors._common','Detector','__init__ factory set_config get_config calc_cartesian_positions calc_mask mask pixel1 pixel2 flatfield darkcurrent orientation','detector','探测器规格、像素/方向与校正图。'),cl('pyFAI','pyFAI.containers','Integrate1dResult','radial intensity sigma','result','读取返回轴/强度/误差，不允许构造伪测量来过验收。','由integrate1d返回。')]+fn('pyFAI','pyFAI','load','io','由PONI重建积分器，检查配置往返。'),sources=src([F+'usage/cookbook/integration_with_python.html',F+'usage/tutorial/Introduction/introduction.html',F+'geometry.html']),
      tasks=[task('07.05.01','integrate_detector_ring','将64×64固定15像素半径环积分为2theta轴，峰应在atan(1.5mm/100mm)=.85937°±.04°；关闭立体角修正后常量图7积分仍为7。','100um像素、距离.1m、中心(32,32)，固定图和几何。',[('构造配置与积分',['pyFAI.integrator.common.Integrator.__init__','pyFAI.integrator.azimuthal.AzimuthalIntegrator.integrate1d']),('读取结果',['pyFAI.containers.Integrate1dResult.radial','pyFAI.containers.Integrate1dResult.intensity'])],['峰角独立atan值','常量强度守恒']),
        task('07.05.01','repair_detector_distance','拒绝距离误写.05m使峰约1.709°；恢复.1m并保存加载PONI，重积分轴/强度等于正确结果。','错误几何副本与固定标定仍存在。',[('保存正确几何并恢复',['pyFAI.geometry.core.Geometry.save','pyFAI.load']),('重积分',['pyFAI.integrator.azimuthal.AzimuthalIntegrator.integrate1d'])],['错误峰偏>.5°','PONI往返恢复同一轴'])]),
      dict(scenario_id='07.05.02',description='以样品方向、波长和角度记录为状态，把XRD扫描转换到倒易空间并连接晶体Q/HKL和网格输出；明确角度deg、Q为Angstrom^-1及旋转顺序，支持可追溯的标定错误修复。',packages=[('xrayutilities','primary','负责衍射几何与材料/倒易变换，避免另一包重算相同Q。')],
      symbols=crystal()+[cl('xrayutilities','xrayutilities.experiment','HXRD','__init__ Ang2Q Q2Ang','geometry','高角共面扫描主几何，保留样品法向和面内参考。'),cl('xrayutilities','xrayutilities.experiment','Experiment','Ang2HKL Transform TiltAngle','geometry','HXRD继承的晶格单位变换与样品方向查询。','HXRD构造后继承，不重复构造基础Experiment。'),cl('xrayutilities','xrayutilities.experiment','QConversion','__init__ point init_linear linear init_area area transformSample2Lab getDetectorPos getDetectorDistance','geometry','需要线/面探测器时补充同框架转换，固定任务只验对称共面。'),cl('xrayutilities','xrayutilities.gridder','Gridder1D','__init__ savetxt dataRange','grid','一维网格范围和保存。'),cl('xrayutilities','xrayutilities.gridder2d','Gridder2D','__init__ savetxt SetResolution dataRange','grid','Q平面网格状态与范围，不额外引入第二插值包。')]+fn('xrayutilities','xrayutilities.utilities','en2lam lam2en','units','显式能量eV/波长Angstrom转换。')+fn('xrayutilities','xrayutilities.io.panalytical_xml','getxrdml_scan getxrdml_map','io','实际实验扫描读取，当前只以制造角度输入验收。'),sources=src([X+'examples.html',X+'xrayutilities.html',X+'simulations.html']),
      tasks=[task('07.05.02','map_symmetric_scan_to_reciprocal_space','把omega10/20/30°和2theta=2omega转换Q，lambda1.54A；验收qx=qy=0、qz=4pi*sin(omega)/lambda。','制造对称共面扫描和方向[100]/[001]。',[('配置并映射',['xrayutilities.experiment.HXRD.__init__','xrayutilities.experiment.HXRD.Ang2Q'])],['qz1.4169658/2.7908778/4.0799905','横向分量0']),
        task('07.05.02','repair_degree_radian_input','诊断把弧度数值传入度数接口导致Q缩小，恢复degrees后重算，并保存带单位的扫描/结果JSON。','原始角度来源10/20/30deg，错误提前转换rad。',[('恢复角度并重算',['xrayutilities.experiment.HXRD.Ang2Q'])],['错误Q显著偏离','恢复独立解析Q和JSON元数据'])]),
      dict(scenario_id='07.05.03',description='将XRR层堆栈、材料光学常数、角度扫描与具名拟合参数联合成薄膜反演环境：xrayutilities是唯一物理正向模型，lmfit负责有界优化。先粗扫避免局部极值，冻结厚度/密度/粗糙度单位与已知项，用独立两界面Fresnel目标验证23nm薄膜厚度及错误边界修复。',packages=[('xrayutilities','primary','层系统、材料光学参数和XRR物理模型。'),('lmfit','complement','具名有界参数/优化/诊断，物理模型不复制。')],
      symbols=[cl('xrayutilities','xrayutilities.simpack.smaterials','Layer','__init__','stack','厚度Angstrom、密度kg/m3与粗糙度构成层状态。'),cl('xrayutilities','xrayutilities.simpack.smaterials','SMaterial','material','stack','层引用材料属性，不把材料与层厚混为同一对象。','由Layer继承。'),cl('xrayutilities','xrayutilities.simpack.smaterials','MaterialList','__init__ check insert','stack','有序层列表构造与受控插入。','LayerStack继承此构造及操作。'),cl('xrayutilities','xrayutilities.simpack.smaterials','LayerStack','check','stack','检查所含层类型和顺序。','继承MaterialList构造。'),cl('xrayutilities','xrayutilities.materials.material','Amorphous','__init__ parseChemForm delta ibeta chi0','material','反射只需化学组成/密度时使用非晶材料表示。'),cl('xrayutilities','xrayutilities.materials.material','Material','idx_refraction critical_angle absorption_length','material','读取材料光学物性和临界角。','具体晶体/非晶材料继承，不单独构造抽象材料。'),cl('xrayutilities','xrayutilities.materials.material','Crystal','fromCIF chi0 chemical_composition','material','固定Si/SiO2材料数据与CIF来源查询。','官方xu.materials预定义材料或fromCIF工厂获取。'),cl('xrayutilities','xrayutilities.simpack.models','SpecularReflectivityModel','__init__ init_cd simulate densityprofile','forward','单一Parratt正向模型及密度分布诊断。'),cl('xrayutilities','xrayutilities.simpack.models','Model','energy convolute_resolution scale_simulation','forward','继承能量、仪器分辨率和强度/背景变换。','由具体反射模型继承。'),cl('lmfit','lmfit.parameter','Parameters','__init__ add add_many copy update valuesdict update_constraints dumps loads','configure','具名参数与约束及持久化。'),cl('lmfit','lmfit.parameter','Parameter','__init__ set value vary expr','configure','固定/变化、边界和参数关系。')]+fn('lmfit','lmfit.minimizer','minimize','fit','对固定物理模型残差求解，粗扫初值后精化。')+fn('lmfit','lmfit.printfuncs','fit_report','diagnose','拟合状态、残差和相关性审阅。')+fn('lmfit','lmfit.confidence','conf_interval','diagnose','只有适用噪声/可识别性条件满足时分析区间，固定无噪声样例未验证校准。'),sources=src([X+'simulations.html',X+'examples.html','https://lmfit.github.io/lmfit-py/examples/example_fit_with_bounds.html']),
      tasks=[task('07.05.03','fit_thin_film_thickness','以固定8keV SiO2/Si独立Fresnel谱为观测，在180..280A粗扫选229A初值后lmfit精化，恢复230A=23nm并验log残差。','151角度点.3..2deg，密度/粗糙度已知固定；oracle光学常数固定。',[('创建层和正向模型',['xrayutilities.simpack.smaterials.Layer.__init__','xrayutilities.simpack.models.SpecularReflectivityModel.__init__','xrayutilities.simpack.models.SpecularReflectivityModel.simulate']),('粗扫后优化',['lmfit.parameter.Parameters.__init__','lmfit.parameter.Parameters.add','lmfit.parameter.Parameter.value','lmfit.minimizer.minimize'])],['厚度230A atol1e-6','正向独立Fresnel误差<1e-14','精化log残差<1e-8']),
        task('07.05.03','repair_thickness_bounds','拒绝厚度上界100A的错误反演，恢复180..280A与粗扫初值，重拟合并参数JSON往返。','错误范围10..100A排除真实230A，验收目标固定。',[('修复参数并优化',['lmfit.parameter.Parameters.__init__','lmfit.parameter.Parameters.add','lmfit.minimizer.minimize']),('保存恢复',['lmfit.parameter.Parameters.dumps','lmfit.parameter.Parameters.loads'])],['错误log残差>.1','恢复230A同一容差'])]),
      dict(scenario_id='07.05.04',description='构建衍射分析的晶体参考状态：选择轻量diffpy.structure统一晶格、原子、占据和位移参数，支持CIF/XYZ读写、实/倒易坐标和原子间几何。pymatgen的重叠结构容器不重复加入；已有pymatgen环境需要桥接时以CIF及明确单位交换。',packages=[('diffpy.structure','primary','以轻量晶体结构/晶格/原子和格式互换为主，避免引入重叠pymatgen结构API。')],
      symbols=[cl('diffpy.structure','diffpy.structure.structure','Structure','__init__ copy add_new_atom get_last_atom get_chemical_symbols get_fractional_coordinates get_cartesian_coordinates get_anisotropic_displacement_parameters get_isotropic_displacement_parameters get_occupancies get_lattice_vectors get_lattice_vector_angles assign_unique_labels distance angle place_in_lattice read read_structure write write_structure tolist append insert extend','structure','原子列表、结构状态、格式读写及几何，只选推荐snake_case而不重复旧别名。'),cl('diffpy.structure','diffpy.structure.lattice','Lattice','__init__ unitvolume set_latt_parms set_new_latt_base_vec cell_parms reciprocal cartesian fractional dot norm rnorm dist angle isanisotropic','lattice','晶格实/倒易坐标、度量和单位/角度修复。'),cl('diffpy.structure','diffpy.structure.atom','Atom','__init__ msd_latt msd_cart xyz_cartn anisotropy U Uisoequiv Bisoequiv','atom','元素/坐标及原子位移参数，不能把occupancy与原子数混淆。')]+fn('diffpy.structure','diffpy.structure','load_structure','io','高层结构读取保留具体格式和原始路径。')+fn('diffpy.structure','diffpy.structure.parsers','get_parser input_formats output_formats','io','格式能力自省和显式解析器入口，防止猜测任意扩展名都受支持。'),sources=src([D+'mod-lattice.html',D+'mod-atom.html',D+'api/diffpy.structure.html']),
      tasks=[task('07.05.04','build_crystal_reference','创建a5.43A的八原子金刚石Si参考并CIF往返，核验体积a^3及最近邻a*sqrt3/4=2.35125897A，保留元素/分数坐标。','FCC四坐标加[.25,.25,.25]构成八原子P1显式结构。',[('构造晶格原子结构',['diffpy.structure.lattice.Lattice.__init__','diffpy.structure.atom.Atom.__init__','diffpy.structure.structure.Structure.__init__','diffpy.structure.structure.Structure.distance']),('保存恢复',['diffpy.structure.structure.Structure.write','diffpy.structure.load_structure'])],['八Si','体积160.103007A³','键长2.3512589713A','CIF分数坐标保持']),
        task('07.05.04','repair_lattice_length_unit','识别把.543nm直接作为Angstrom造成键长缩小10倍，将晶格长度恢复5.43A后重新计算；不改变分数坐标来遮掩单位错误。','原尺度来源与分数位置保留。',[('复制和修复晶格',['diffpy.structure.structure.Structure.__init__','diffpy.structure.lattice.Lattice.__init__']),('重新验收距离',['diffpy.structure.structure.Structure.distance'])],['错误键长偏差>2A','恢复解析键长'])])]
    for d in designs:
        if d['scenario_id'] in ['07.05.01','07.05.02','07.05.03','07.05.04']:
            d['count_exception']='高层参考动作按定义处保留继承接口，不重复构造/属性和旧API别名；若低于50则以已闭合的文件/配置/分析/独立验收/修复链为准，不加入不相关机械性质或重复反射求解器凑数。'
        d['capabilities']=list(dict.fromkeys(s['capability'] for s in d['symbols']))
        d['entities']=[{'name':'measurement_source','identity':'scan/image/source_id','attributes':['path','hash','detector_orientation','angles','intensity','unit','revision'],'lifecycle':'读入→保留原始数据→核对单位/方向→派生处理，源更改需重新验收。'},
          {'name':'geometry_or_crystal','identity':'configuration_id','attributes':['wavelength','PONI','sample_axes','lattice','atoms','units','calibration_source'],'lifecycle':'构造→按独立几何核对→版本冻结；错误单位修复后旧Q/谱失效。'},
          {'name':'layer_or_fit_model','identity':'model_id','attributes':['ordered_layers','density','roughness','thickness_A','fixed_parameters','bounds','coarse_grid'],'lifecycle':'配置→粗扫/正向→拟合→固定oracle；缺少密度等信息时不能声称联合参数唯一性。'},
          {'name':'analysis_result','identity':'result_id','attributes':['source_refs','radial_or_Q_axis','curve','parameters','residual','validation'],'lifecycle':'生成→解析/几何/守恒检查→PONI/CIF/JSON保存恢复，容差事前固定。'}]
        d['bridges']=[{'from':'rawdetector/angles or crystal/orderedlayers','to':'pyFAIintegral / xrayutilitiesQ or XRR / lmfitnamedresidual / diffpyCIF accordingto selectedpackages','contract':'pyFAI长度m、XRR层厚与晶格A、角度deg、Q为A^-1；层序从基底到表面；物理常数和观测版本绑定。'}]
        d['runtime_infrastructure']=[{'reference':'python.numpy_json_math_pathlib','kind':'infrastructure','reason':'固定制造环/原子/扫描，独立atan/倒易几何/Fresnel公式和参数粗扫循环；包正向与优化单独作为已选动作。'},
          {'reference':'runtime.scientific_object_attributes','kind':'infrastructure','reason':'对象属性如layer.thickness、Structure.lattice/xyz/element和Lattice.volume读取；源AST未将普通实例属性伪造为类方法。'}]
        d['boundaries']=['仅四组制造固定数据任务，不是真实束线/探测器标定、全部反射模型或所有文件格式运行覆盖。','XRR独立目标使用固定8keV材料chi与两界面公式；仅厚度变化，未验证密度/粗糙度联合可识别性或噪声置信度。','pyFAI官方HTTPS文档证书链失败，未关闭TLS校验，采用官方HTTP文档并保留URL。','未实现Agent持久状态、reset/step、跨任务隔离和硬件/远程权限，当前文件仅本地样例输出。']
        d['runtime_report']=(BASE/f'runtime/xrd/{d["scenario_id"]}.json').as_posix();d['runtime_scope']='固定制造正常、故障修复各一条任务；独立几何/材料常数/Fresneloracle，明确运行子集。'
        c.write(d)
if __name__=='__main__':main()
